export const adrStrings = {
    label: 'Architecture decisions',
    noProject: 'Select a project to read its architecture decisions.',
    loading: 'Loading decisions…',
    refresh: 'Refresh',
    retry: 'Try again',
    edit: 'Edit',
    add: 'Add decision',
    create: 'Create decision record',
    emptyTitle: 'Record the decisions behind this project.',
    emptyBody: 'Keep context, alternatives, and consequences together in a Markdown document shared with your agents.',
    save: 'Save',
    saving: 'Saving…',
    saved: 'Saved',
    cancel: 'Cancel',
    preview: 'Preview',
    hidePreview: 'Hide preview',
    editor: 'Decision record Markdown',
    document: 'Decision document',
    outline: 'On this page',
    draft: 'Unsaved draft',
    restored: 'Draft restored. Changes are saved only when you choose Save.',
    edited: 'Updated',
    noDate: 'Markdown document',
    readFailed: 'Could not load the decision record. Try again.',
    saveFailed: 'Could not save. Your draft is intact; try again.',
    checkFailed: 'Could not check the latest version. Your draft is intact; try again.',
    verifyFailed: 'The save could not be verified. Your draft is intact; try again.',
    busy: 'The project is busy. Wait for indexing to finish, then try again.',
    conflict: 'The server document changed. Review the latest version before saving your draft.',
    mismatch: 'The server returned different content after saving. Your draft is intact; review the latest version.',
    review: 'Review latest version',
    hideReview: 'Hide latest version',
    latest: 'Latest server version',
    latestEmpty: 'The server returned no document content.',
    reload: 'Discard draft and load latest',
    rebase: 'Use latest as edit base',
    rebased: 'Your draft remains in the editor. Incorporate the reviewed changes before saving.',
    storageUnavailable: 'The draft is kept for this page session, but browser storage is unavailable. Keep this page open until you save.',
    size: (bytes: number) => `${bytes.toLocaleString('en-US')} / 8,000 bytes`,
    sizeExceeded: 'Keep the document within 8,000 UTF-8 bytes.',
    bodyExceeded: 'The encoded save request is too large. Shorten the document before saving.',
};
