export const activityStrings = {
    title: 'Agent activity', subtitle: 'Follow recorded work and inspect the code it touches.',
    connect: 'Load recorded activity', disconnect: 'Disconnect', agent: 'Agent', run: 'Run', kind: 'Activity',
    allAgents: 'All agents', allRuns: 'All runs', allKinds: 'All activity', search: 'Filter activity',
    placeholder: 'Search tools, paths, or details…', events: 'Recorded events', actors: 'Agents seen',
    gaps: 'Missing sequence numbers', dropped: 'Connection drops', unmapped: 'Unmapped',
    noSource: 'Load recorded activity from this daemon. Hooks send events to /api/agent-events on the same port.',
    noEvents: 'No recorded activity for this repository. Configure the tool hook with the indexed project name; tool calls are observed, never inferred.', noMatch: 'No activity matches these filters.',
    clear: 'Clear filters', evidence: 'Event evidence', open: 'Open source', select: 'Select an event to inspect its evidence.',
    retained: 'Showing retained history: up to 80 events per agent. Counts are observed totals, not task progress.',
    outcome: 'An end event records the end of a tool call. Its result is not reported by this stream.',
    mapping: 'Mapping', timestamp: 'Recorded time', source: 'Source', phase: 'Phase', details: 'Details',
    replay: 'Replay', live: 'Recorded', unknown: 'Not reported', reset: 'Reset',
    disconnected: 'Stream is off. Retained events remain available.',
    limited: 'Graph placement uses the loaded map. Unmapped events remain visible.',
    noGraphMatch: 'No matching location in the loaded graph. The index may contain more nodes.',
    unreadable: 'Unreadable records skipped by the stream',
    kinds: ['read', 'write', 'search', 'test', 'other'] as const,
};
