version: "2"
run:
  go: "1.26"
linters:
  enable:
    - bodyclose
    - cyclop
    - durationcheck
    - funlen
    - gocognit
    - gocritic
    - gosec
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
  settings:
    cyclop:
      max-complexity: 25
    errcheck:
      check-type-assertions: true
    funlen:
      lines: 120
      statements: 80
    gocognit:
      min-complexity: 30
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    gosec:
      excludes:
        - G115
        - G404
        - G704
        - G705
        - G706
    nestif:
      min-complexity: 6
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
