export type Workspace = 'explore' | 'galaxy' | 'architecture' | 'agents' | 'system';
export type Guidance = 'brief' | 'explained';

export const workspaceStrings = {
    navigation: 'Workspace',
    workspaces: [
        { id: 'explore' as const, label: 'Explore' },
        { id: 'galaxy' as const, label: 'Galaxy' },
        { id: 'architecture' as const, label: 'Architecture' },
        { id: 'agents' as const, label: 'Agents' },
        { id: 'system' as const, label: 'System' },
    ],
    tools: 'Tools',
    search: 'Search',
    searchOpen: 'Open search and commands',
    searchTitle: 'Search and commands',
    searchPlaceholder: 'Find a symbol, search by meaning, or run a command',
    searchClose: 'Close search',
    loadedSearchHeadline: (query: string, count: number) => `${count} loaded ${count === 1 ? 'match' : 'matches'} for "${query}"; no matching index results.`,
    searchShortcut: '⌘ / Ctrl K',
    searchExamples: 'Try a search or graph command',
    chatGraphHeight: 'Height of graph below chat',
    guidance: 'Explanation depth',
    brief: 'Brief',
    briefValue: 'brief',
    explained: 'Explained',
    explainedValue: 'explained',
    diagnostics: 'Connection details',
    coverage: 'Index details',
    model: 'Model details',
    perspective: 'Reading preferences',
    welcomeEyebrow: 'Codebase memory',
    welcomeTitle: 'A clearer view of your code.',
    welcomeDescription: 'Explore the source, understand its architecture, and follow your agents.',
    descriptions: {
        explore: 'Read source with graph context.',
        galaxy: 'Explore the whole graph and its coverage shadow.',
        architecture: 'See modules, dependencies, and entry points.',
        agents: 'Inspect recorded activity and touched code.',
        system: 'Monitor the daemon, indexes, and logs.',
    },
    changeLater: 'Switch workspaces and explanation depth at any time. Every feature stays available.',
    localAi: 'Set up browser AI',
    browserAi: 'Chat',
    daemon: 'Daemon',
    daemonNavigation: (state: string) => `Open System: daemon ${state}`,
    chatWidth: 'Width of local chat',
    askSelection: 'Ask about selection',
    graphContext: 'Graph context',
    coverageShadowSelection: (name: string) => `Coverage shadow: ${name}`,
    start: 'Start exploring',
    aiOptional: 'Browser AI is optional and off. Setup asks before downloading a model.',
};
