/*
 * test_depindex.c — Tests for dependency/reference API indexing.
 *
 * Covers: package resolution, dependency discovery, external node marking,
 *         QN prefixing, separate storage, AI grounding safeguards.
 *
 * TDD: All tests written BEFORE implementation. They should fail (RED)
 * until the corresponding feature is implemented (GREEN).
 */
#include "../src/foundation/compat.h"
#include "test_framework.h"
#include <mcp/mcp.h>
#include <store/store.h>
#include <depindex/depindex.h>
#include <yyjson/yyjson.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/stat.h>
#include <unistd.h>

/* ── Helpers ─────────────────────────────────────────────────── */

static char *extract_text_content_di(const char *mcp_result) {
    if (!mcp_result)
        return NULL;
    yyjson_doc *doc = yyjson_read(mcp_result, strlen(mcp_result), 0);
    if (!doc)
        return strdup(mcp_result);
    yyjson_val *root = yyjson_doc_get_root(doc);
    yyjson_val *content = yyjson_obj_get(root, "content");
    if (!content || !yyjson_is_arr(content)) {
        yyjson_doc_free(doc);
        return strdup(mcp_result);
    }
    yyjson_val *item = yyjson_arr_get(content, 0);
    if (!item) {
        yyjson_doc_free(doc);
        return strdup(mcp_result);
    }
    yyjson_val *text = yyjson_obj_get(item, "text");
    const char *str = yyjson_get_str(text);
    char *result = str ? strdup(str) : strdup(mcp_result);
    yyjson_doc_free(doc);
    return result;
}

/* Create a temp dir with a fake cargo project structure for testing. */
static int __attribute__((unused)) setup_cargo_fixture(char *tmp_dir, size_t tmp_sz) {
    snprintf(tmp_dir, tmp_sz, "/tmp/cbm_deptest_XXXXXX");
    if (!cbm_mkdtemp(tmp_dir))
        return -1;

    char proj_dir[512];
    snprintf(proj_dir, sizeof(proj_dir), "%s/project", tmp_dir);
    cbm_mkdir(proj_dir);

    /* Write a Cargo.lock with a serde entry */
    char lock_path[512];
    snprintf(lock_path, sizeof(lock_path), "%s/Cargo.lock", proj_dir);
    FILE *fp = fopen(lock_path, "w");
    if (!fp)
        return -1;
    fprintf(fp, "# This file is automatically @generated by Cargo.\n"
                "[[package]]\n"
                "name = \"my-project\"\n"
                "version = \"0.1.0\"\n\n"
                "[[package]]\n"
                "name = \"serde\"\n"
                "version = \"1.0.200\"\n"
                "source = \"registry+https://github.com/rust-lang/crates.io-index\"\n\n"
                "[[package]]\n"
                "name = \"tokio\"\n"
                "version = \"1.37.0\"\n"
                "source = \"registry+https://github.com/rust-lang/crates.io-index\"\n");
    fclose(fp);

    /* Write a simple src/main.rs */
    char src_dir[512];
    snprintf(src_dir, sizeof(src_dir), "%s/src", proj_dir);
    cbm_mkdir(src_dir);
    char main_path[512];
    snprintf(main_path, sizeof(main_path), "%s/main.rs", src_dir);
    fp = fopen(main_path, "w");
    if (!fp)
        return -1;
    fprintf(fp, "use serde::Serialize;\n\n"
                "fn main() {\n"
                "    println!(\"hello\");\n"
                "}\n");
    fclose(fp);

    return 0;
}

/* Create a temp dir with fake Python venv structure. */
static int __attribute__((unused)) setup_uv_fixture(char *tmp_dir, size_t tmp_sz) {
    snprintf(tmp_dir, tmp_sz, "/tmp/cbm_uvtest_XXXXXX");
    if (!cbm_mkdtemp(tmp_dir))
        return -1;

    char proj_dir[512];
    snprintf(proj_dir, sizeof(proj_dir), "%s/project", tmp_dir);
    cbm_mkdir(proj_dir);

    /* Create .venv/lib/python3.12/site-packages/requests/ */
    char venv_path[512];
    snprintf(venv_path, sizeof(venv_path), "%s/.venv", proj_dir);
    cbm_mkdir(venv_path);
    snprintf(venv_path, sizeof(venv_path), "%s/.venv/lib", proj_dir);
    cbm_mkdir(venv_path);
    snprintf(venv_path, sizeof(venv_path), "%s/.venv/lib/python3.12", proj_dir);
    cbm_mkdir(venv_path);
    snprintf(venv_path, sizeof(venv_path), "%s/.venv/lib/python3.12/site-packages", proj_dir);
    cbm_mkdir(venv_path);
    snprintf(venv_path, sizeof(venv_path),
             "%s/.venv/lib/python3.12/site-packages/requests", proj_dir);
    cbm_mkdir(venv_path);

    /* Write a simple __init__.py */
    char init_path[512];
    snprintf(init_path, sizeof(init_path), "%s/__init__.py", venv_path);
    FILE *fp = fopen(init_path, "w");
    if (!fp)
        return -1;
    fprintf(fp, "\"\"\"Requests library.\"\"\"\n\n"
                "def get(url, **kwargs):\n"
                "    \"\"\"Send a GET request.\"\"\"\n"
                "    pass\n\n"
                "def post(url, data=None, **kwargs):\n"
                "    \"\"\"Send a POST request.\"\"\"\n"
                "    pass\n");
    fclose(fp);

    return 0;
}

static void cleanup_fixture_dir(const char *tmp_dir) {
    /* Best-effort recursive cleanup via system command */
    char cmd[512];
    snprintf(cmd, sizeof(cmd), "rm -rf '%s' 2>/dev/null", tmp_dir);
    (void)system(cmd);
}

/* Create an MCP server with a project indexed, for testing query integration. */
static cbm_mcp_server_t *setup_dep_query_server(char *tmp_dir, size_t tmp_sz) {
    snprintf(tmp_dir, tmp_sz, "/tmp/cbm_depquery_XXXXXX");
    if (!cbm_mkdtemp(tmp_dir))
        return NULL;

    char proj_dir[512];
    snprintf(proj_dir, sizeof(proj_dir), "%s/project", tmp_dir);
    cbm_mkdir(proj_dir);

    /* Write source file */
    char src_path[512];
    snprintf(src_path, sizeof(src_path), "%s/app.py", proj_dir);
    FILE *fp = fopen(src_path, "w");
    if (!fp)
        return NULL;
    fprintf(fp, "import pandas as pd\n\n"
                "def process_data():\n"
                "    df = pd.DataFrame()\n"
                "    return df\n");
    fclose(fp);

    cbm_mcp_server_t *srv = cbm_mcp_server_new(NULL);
    if (!srv)
        return NULL;

    cbm_store_t *st = cbm_mcp_server_store(srv);
    if (!st) {
        cbm_mcp_server_free(srv);
        return NULL;
    }

    const char *proj_name = "dep-query-test";
    cbm_mcp_server_set_project(srv, proj_name);
    cbm_store_upsert_project(st, proj_name, proj_dir);

    /* Create project node */
    cbm_node_t n_proc = {0};
    n_proc.project = proj_name;
    n_proc.label = "Function";
    n_proc.name = "process_data";
    n_proc.qualified_name = "dep-query-test.app.process_data";
    n_proc.file_path = "app.py";
    n_proc.start_line = 3;
    n_proc.end_line = 5;
    n_proc.properties_json = "{\"is_exported\":true}";
    cbm_store_upsert_node(st, &n_proc);

    return srv;
}

/* ══════════════════════════════════════════════════════════════════
 *  PACKAGE RESOLUTION (requires depindex.h — will fail until implemented)
 * ══════════════════════════════════════════════════════════════════ */

/*
 * NOTE: Package resolution tests depend on src/depindex/depindex.h which
 * does not exist yet. These tests will cause compilation errors until
 * Feature 2 implementation begins. For the RED phase, we test only the
 * MCP-level behavior via the server handle interface.
 */

/* ══════════════════════════════════════════════════════════════════
 *  MCP TOOL: index_dependencies (via server handle)
 * ══════════════════════════════════════════════════════════════════ */

TEST(tool_index_dependencies_listed) {
    char *json = cbm_mcp_tools_list(NULL);
    ASSERT_NOT_NULL(json);
    /* In streamlined mode (NULL srv), index_dependencies is hidden.
     * But search_code_graph (consolidated) should be present. */
    ASSERT_NOT_NULL(strstr(json, "search_code_graph"));
    free(json);
    PASS();
}

TEST(tool_index_dependencies_missing_project) {
    cbm_mcp_server_t *srv = cbm_mcp_server_new(NULL);

    char *resp = cbm_mcp_server_handle(
        srv, "{\"jsonrpc\":\"2.0\",\"id\":50,\"method\":\"tools/call\","
             "\"params\":{\"name\":\"index_dependencies\","
             "\"arguments\":{\"package_manager\":\"cargo\"}}}");
    ASSERT_NOT_NULL(resp);
    /* Should require project parameter */
    ASSERT_NOT_NULL(strstr(resp, "required"));
    free(resp);

    cbm_mcp_server_free(srv);
    PASS();
}

TEST(tool_index_dependencies_missing_packages) {
    cbm_mcp_server_t *srv = cbm_mcp_server_new(NULL);

    /* packages[] is now required */
    char *resp = cbm_mcp_server_handle(
        srv, "{\"jsonrpc\":\"2.0\",\"id\":51,\"method\":\"tools/call\","
             "\"params\":{\"name\":\"index_dependencies\","
             "\"arguments\":{\"project\":\"test\"}}}");
    ASSERT_NOT_NULL(resp);
    ASSERT_NOT_NULL(strstr(resp, "required"));
    free(resp);

    cbm_mcp_server_free(srv);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  AI GROUNDING: DEFAULT QUERY EXCLUDES DEPENDENCIES
 * ══════════════════════════════════════════════════════════════════ */

TEST(search_graph_default_excludes_deps) {
    char tmp[256];
    cbm_mcp_server_t *srv = setup_dep_query_server(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    /* Default search_graph (no include_dependencies) should only return
     * project code — NEVER dependency code. This is the MOST IMPORTANT
     * test for AI grounding. */
    char *raw = cbm_mcp_handle_tool(srv, "search_graph",
                                    "{\"project\":\"dep-query-test\","
                                    "\"label\":\"Function\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    /* Should find process_data (project code) */
    ASSERT_NOT_NULL(strstr(resp, "process_data"));
    /* Should NOT find any dep.* qualified names */
    ASSERT_NULL(strstr(resp, "\"dep."));
    /* Should NOT find external:true markers */
    ASSERT_NULL(strstr(resp, "\"external\":true"));

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(search_graph_include_deps_marks_source) {
    char tmp[256];
    cbm_mcp_server_t *srv = setup_dep_query_server(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    /* With include_dependencies=true, results should have source field */
    char *raw = cbm_mcp_handle_tool(srv, "search_graph",
                                    "{\"project\":\"dep-query-test\","
                                    "\"label\":\"Function\","
                                    "\"include_dependencies\":true}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    /* Project results should have source:"project" */
    ASSERT_NOT_NULL(strstr(resp, "\"source\":\"project\""));

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(trace_call_path_marks_boundary) {
    char tmp[256];
    cbm_mcp_server_t *srv = setup_dep_query_server(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    /* trace_call_path with include_dependencies should mark boundary */
    char *raw = cbm_mcp_handle_tool(srv, "trace_call_path",
                                    "{\"function_name\":\"process_data\","
                                    "\"project\":\"dep-query-test\","
                                    "\"include_dependencies\":true}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    /* Response should exist (even if no deps indexed yet, should not crash) */
    ASSERT_NOT_NULL(strstr(resp, "process_data"));

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(get_code_snippet_dep_shows_provenance) {
    char tmp[256];
    cbm_mcp_server_t *srv = setup_dep_query_server(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    /* Requesting a dep symbol should show package provenance */
    char *raw = cbm_mcp_handle_tool(srv, "get_code_snippet",
                                    "{\"qualified_name\":\"dep.uv.pandas.DataFrame\","
                                    "\"project\":\"dep-query-test\","
                                    "\"include_dependencies\":true}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);
    /* Without deps indexed, should return not found — that's fine.
     * The key test is that include_dependencies doesn't crash. */

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  EXTERNAL NODE MARKING
 * ══════════════════════════════════════════════════════════════════ */

TEST(build_def_props_no_external_when_null_ctx) {
    /* Normal indexing (dep_ctx=NULL) should NOT add external metadata.
     * We test this indirectly: index a project, check properties. */
    cbm_mcp_server_t *srv = cbm_mcp_server_new(NULL);
    cbm_store_t *st = cbm_mcp_server_store(srv);

    cbm_node_t n = {0};
    n.project = "test";
    n.label = "Function";
    n.name = "my_func";
    n.qualified_name = "test.my_func";
    n.file_path = "test.py";
    n.start_line = 1;
    n.end_line = 3;
    n.properties_json = "{\"is_exported\":true}";
    cbm_store_upsert_node(st, &n);

    /* Properties should NOT contain "external" */
    ASSERT_NULL(strstr(n.properties_json, "external"));

    cbm_mcp_server_free(srv);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  QN PREFIXING
 * ══════════════════════════════════════════════════════════════════ */

TEST(dep_qn_no_collision_with_project) {
    /* If project has module "pandas" and dep has package "pandas",
     * their QNs must not collide.
     * Project: "my-project.pandas.helper"
     * Dep:     "dep.uv.pandas.DataFrame"
     * These are clearly different prefixes. */
    const char *proj_qn = "my-project.pandas.helper";
    const char *dep_qn = "dep.uv.pandas.DataFrame";
    ASSERT_TRUE(strncmp(proj_qn, dep_qn, 4) != 0); /* "my-p" != "dep." */
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  SEPARATE STORAGE
 * ══════════════════════════════════════════════════════════════════ */

TEST(dep_db_path_convention) {
    /* Verify the naming convention: {project}_deps.db */
    const char *project = "my-project";
    char expected[256];
    snprintf(expected, sizeof(expected), "%s_deps.db", project);
    ASSERT_STR_EQ(expected, "my-project_deps.db");
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  DEPENDENCY DISCOVERY (file filtering)
 * ══════════════════════════════════════════════════════════════════ */

TEST(dep_discover_skips_test_dirs) {
    char tmp[256];
    snprintf(tmp, sizeof(tmp), "/tmp/cbm_disc_test_XXXXXX");
    if (!cbm_mkdtemp(tmp)) {
        SKIP("Could not create temp dir");
    }

    /* Create src/lib.rs and tests/test_foo.rs */
    char src_dir[512], test_dir[512];
    snprintf(src_dir, sizeof(src_dir), "%s/src", tmp);
    cbm_mkdir(src_dir);
    snprintf(test_dir, sizeof(test_dir), "%s/tests", tmp);
    cbm_mkdir(test_dir);

    char path[512];
    snprintf(path, sizeof(path), "%s/lib.rs", src_dir);
    FILE *fp = fopen(path, "w");
    if (fp) { fprintf(fp, "pub fn hello() {}\n"); fclose(fp); }

    snprintf(path, sizeof(path), "%s/test_foo.rs", test_dir);
    fp = fopen(path, "w");
    if (fp) { fprintf(fp, "#[test]\nfn test_foo() {}\n"); fclose(fp); }

    /* When dependency discovery is implemented, it should skip tests/ */
    /* For now, just verify the fixture was created correctly */
    snprintf(path, sizeof(path), "%s/lib.rs", src_dir);
    fp = fopen(path, "r");
    ASSERT_NOT_NULL(fp);
    fclose(fp);

    snprintf(path, sizeof(path), "%s/test_foo.rs", test_dir);
    fp = fopen(path, "r");
    ASSERT_NOT_NULL(fp);
    fclose(fp);

    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(dep_discover_max_files_guard) {
    /* Verify concept: if a package has >1000 files, we cap at 1000.
     * We won't create 1000 files in the test — just verify the constant. */
    int max_files_default = 1000;
    ASSERT_EQ(max_files_default, 1000);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  FIXTURE: Project + dep nodes in same db for integration tests
 * ══════════════════════════════════════════════════════════════════ */

/* Create an MCP server with project AND dep nodes indexed. */
static cbm_mcp_server_t *setup_proj_with_deps(char *tmp_dir, size_t tmp_sz) {
    snprintf(tmp_dir, tmp_sz, "/tmp/cbm_depfull_XXXXXX");
    if (!cbm_mkdtemp(tmp_dir))
        return NULL;

    char proj_dir[512];
    snprintf(proj_dir, sizeof(proj_dir), "%s/project", tmp_dir);
    cbm_mkdir(proj_dir);

    /* Write a source file */
    char src_path[512];
    snprintf(src_path, sizeof(src_path), "%s/app.py", proj_dir);
    FILE *fp = fopen(src_path, "w");
    if (!fp) return NULL;
    fprintf(fp, "import pandas as pd\ndef process_data():\n    return pd.DataFrame()\n");
    fclose(fp);

    cbm_mcp_server_t *srv = cbm_mcp_server_new(NULL);
    if (!srv) return NULL;
    cbm_store_t *st = cbm_mcp_server_store(srv);
    if (!st) { cbm_mcp_server_free(srv); return NULL; }

    const char *proj_name = "testproj";
    cbm_mcp_server_set_project(srv, proj_name);
    cbm_mcp_server_set_session_project(srv, proj_name);
    cbm_store_upsert_project(st, proj_name, proj_dir);

    /* Project node */
    cbm_node_t n1 = {0};
    n1.project = proj_name;
    n1.label = "Function";
    n1.name = "process_data";
    n1.qualified_name = "testproj.app.process_data";
    n1.file_path = "app.py";
    n1.start_line = 2;
    n1.end_line = 3;
    n1.properties_json = "{\"is_exported\":true}";
    cbm_store_upsert_node(st, &n1);

    /* Dep nodes */
    cbm_store_upsert_project(st, "testproj.dep.pandas", "/tmp/pandas");

    cbm_node_t n_df = {0};
    n_df.project = "testproj.dep.pandas";
    n_df.label = "Class";
    n_df.name = "DataFrame";
    n_df.qualified_name = "testproj.dep.pandas.DataFrame";
    n_df.file_path = "pandas/core/frame.py";
    n_df.start_line = 100;
    n_df.end_line = 500;
    n_df.properties_json = "{\"is_exported\":true}";
    cbm_store_upsert_node(st, &n_df);

    cbm_node_t n_read = {0};
    n_read.project = "testproj.dep.pandas";
    n_read.label = "Function";
    n_read.name = "read_csv";
    n_read.qualified_name = "testproj.dep.pandas.read_csv";
    n_read.file_path = "pandas/io/parsers.py";
    n_read.start_line = 50;
    n_read.end_line = 80;
    n_read.properties_json = "{\"is_exported\":true}";
    cbm_store_upsert_node(st, &n_read);

    return srv;
}

/* ══════════════════════════════════════════════════════════════════
 *  DEPINDEX HELPER UNIT TESTS
 * ══════════════════════════════════════════════════════════════════ */

#include <depindex/depindex.h>
#include <pipeline/pipeline.h>

TEST(test_parse_pkg_manager_valid) {
    ASSERT_EQ(cbm_parse_pkg_manager("uv"), CBM_PKG_UV);
    ASSERT_EQ(cbm_parse_pkg_manager("pip"), CBM_PKG_UV);
    ASSERT_EQ(cbm_parse_pkg_manager("cargo"), CBM_PKG_CARGO);
    ASSERT_EQ(cbm_parse_pkg_manager("npm"), CBM_PKG_NPM);
    ASSERT_EQ(cbm_parse_pkg_manager("bun"), CBM_PKG_BUN);
    ASSERT_EQ(cbm_parse_pkg_manager("custom"), CBM_PKG_CUSTOM);
    PASS();
}

TEST(test_parse_pkg_manager_invalid) {
    ASSERT_EQ(cbm_parse_pkg_manager("nonexistent"), CBM_PKG_COUNT);
    ASSERT_EQ(cbm_parse_pkg_manager(NULL), CBM_PKG_COUNT);
    ASSERT_EQ(cbm_parse_pkg_manager(""), CBM_PKG_COUNT);
    PASS();
}

TEST(test_pkg_manager_str_roundtrip) {
    ASSERT_STR_EQ(cbm_pkg_manager_str(CBM_PKG_UV), "uv");
    ASSERT_STR_EQ(cbm_pkg_manager_str(CBM_PKG_CARGO), "cargo");
    ASSERT_STR_EQ(cbm_pkg_manager_str(CBM_PKG_NPM), "npm");
    ASSERT_STR_EQ(cbm_pkg_manager_str(CBM_PKG_COUNT), "unknown");
    PASS();
}

TEST(test_dep_project_name_format) {
    char *name = cbm_dep_project_name("myapp", "pandas");
    ASSERT_NOT_NULL(name);
    ASSERT_STR_EQ(name, "myapp.dep.pandas");
    free(name);

    name = cbm_dep_project_name("myapp", "serde");
    ASSERT_NOT_NULL(name);
    ASSERT_STR_EQ(name, "myapp.dep.serde");
    free(name);

    /* NULL inputs */
    ASSERT_NULL(cbm_dep_project_name(NULL, "pandas"));
    ASSERT_NULL(cbm_dep_project_name("myapp", NULL));
    PASS();
}

TEST(test_is_dep_project_with_session) {
    /* With session context — precise prefix check */
    ASSERT_TRUE(cbm_is_dep_project("myapp.dep.pandas", "myapp"));
    ASSERT_TRUE(cbm_is_dep_project("myapp.dep.serde", "myapp"));
    ASSERT_FALSE(cbm_is_dep_project("myapp", "myapp"));
    ASSERT_FALSE(cbm_is_dep_project("otherapp.dep.pandas", "myapp"));
    ASSERT_FALSE(cbm_is_dep_project(NULL, "myapp"));
    PASS();
}

TEST(test_is_dep_project_without_session) {
    /* Without session context — fallback strstr check */
    ASSERT_TRUE(cbm_is_dep_project("myapp.dep.pandas", NULL));
    ASSERT_TRUE(cbm_is_dep_project("dep.cargo.serde", NULL));
    ASSERT_FALSE(cbm_is_dep_project("myapp", NULL));
    ASSERT_FALSE(cbm_is_dep_project("deputy", NULL));
    PASS();
}

TEST(test_detect_ecosystem_python) {
    char tmp[256];
    snprintf(tmp, sizeof(tmp), "/tmp/cbm_eco_py_XXXXXX");
    if (!cbm_mkdtemp(tmp)) { SKIP("Could not create temp dir"); }
    char path[512];
    snprintf(path, sizeof(path), "%s/pyproject.toml", tmp);
    FILE *fp = fopen(path, "w");
    if (fp) { fprintf(fp, "[project]\nname = \"test\"\n"); fclose(fp); }
    ASSERT_EQ(cbm_detect_ecosystem(tmp), CBM_PKG_UV);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_detect_ecosystem_rust) {
    char tmp[256];
    snprintf(tmp, sizeof(tmp), "/tmp/cbm_eco_rs_XXXXXX");
    if (!cbm_mkdtemp(tmp)) { SKIP("Could not create temp dir"); }
    char path[512];
    snprintf(path, sizeof(path), "%s/Cargo.toml", tmp);
    FILE *fp = fopen(path, "w");
    if (fp) { fprintf(fp, "[package]\nname = \"test\"\n"); fclose(fp); }
    ASSERT_EQ(cbm_detect_ecosystem(tmp), CBM_PKG_CARGO);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_detect_ecosystem_none) {
    char tmp[256];
    snprintf(tmp, sizeof(tmp), "/tmp/cbm_eco_none_XXXXXX");
    if (!cbm_mkdtemp(tmp)) { SKIP("Could not create temp dir"); }
    ASSERT_EQ(cbm_detect_ecosystem(tmp), CBM_PKG_COUNT);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_is_manifest_path) {
    ASSERT_TRUE(cbm_is_manifest_path("src/Cargo.toml"));
    ASSERT_TRUE(cbm_is_manifest_path("/Users/x/myapp/pyproject.toml"));
    ASSERT_TRUE(cbm_is_manifest_path("package.json"));
    ASSERT_FALSE(cbm_is_manifest_path("src/main.rs"));
    ASSERT_FALSE(cbm_is_manifest_path(NULL));
    PASS();
}

TEST(test_resolve_npm_node_modules) {
    char tmp[256];
    snprintf(tmp, sizeof(tmp), "/tmp/cbm_resolve_npm_XXXXXX");
    if (!cbm_mkdtemp(tmp)) { SKIP("Could not create temp dir"); }

    /* Create node_modules/react/ with package.json */
    char nm[512];
    snprintf(nm, sizeof(nm), "%s/node_modules", tmp);
    cbm_mkdir(nm);
    snprintf(nm, sizeof(nm), "%s/node_modules/react", tmp);
    cbm_mkdir(nm);
    char pj[512];
    snprintf(pj, sizeof(pj), "%s/package.json", nm);
    FILE *fp = fopen(pj, "w");
    if (fp) { fprintf(fp, "{\"name\":\"react\",\"version\":\"18.2.0\"}\n"); fclose(fp); }

    cbm_dep_resolved_t out = {0};
    ASSERT_EQ(cbm_resolve_pkg_source(CBM_PKG_NPM, "react", tmp, &out), 0);
    ASSERT_NOT_NULL(out.path);
    ASSERT_NOT_NULL(strstr(out.path, "node_modules/react"));
    cbm_dep_resolved_free(&out);

    /* Non-existent package */
    cbm_dep_resolved_t out2 = {0};
    ASSERT_EQ(cbm_resolve_pkg_source(CBM_PKG_NPM, "nonexistent", tmp, &out2), -1);

    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_pipeline_set_project_name) {
    cbm_pipeline_t *p = cbm_pipeline_new("/tmp", NULL, CBM_MODE_FULL);
    ASSERT_NOT_NULL(p);
    const char *orig = cbm_pipeline_project_name(p);
    ASSERT_NOT_NULL(orig);
    /* Set custom name */
    cbm_pipeline_set_project_name(p, "myapp.dep.pandas");
    ASSERT_STR_EQ(cbm_pipeline_project_name(p), "myapp.dep.pandas");
    cbm_pipeline_free(p);
    PASS();
}

TEST(test_dep_reindex_replaces) {
    /* Verify upsert replaces old nodes for same QN, not duplicates. */
    cbm_store_t *store = cbm_store_open_memory();
    ASSERT_NOT_NULL(store);

    /* Must register project first (foreign key) */
    cbm_store_upsert_project(store, "test.dep.pandas", "/tmp/pandas");

    cbm_node_t n1 = {0};
    n1.project = "test.dep.pandas";
    n1.label = "Function";
    n1.name = "old_func";
    n1.qualified_name = "test.dep.pandas.old_func";
    n1.file_path = "pandas/__init__.py";
    n1.start_line = 1;
    n1.end_line = 3;
    n1.properties_json = "{}";
    cbm_store_upsert_node(store, &n1);

    int count1 = cbm_store_count_nodes(store, "test.dep.pandas");
    ASSERT_EQ(count1, 1);

    /* Upsert with same QN — should not duplicate */
    cbm_store_upsert_node(store, &n1);
    int count2 = cbm_store_count_nodes(store, "test.dep.pandas");
    ASSERT_EQ(count2, 1);

    cbm_store_close(store);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  RESULT TAGGING: source field on all search results
 * ══════════════════════════════════════════════════════════════════ */

TEST(test_search_results_have_source_field) {
    /* ALL search results must have source:"project" or source:"dependency" */
    char tmp[256];
    cbm_mcp_server_t *srv = setup_proj_with_deps(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    /* Search with no project filter — should return both project + dep nodes */
    char *raw = cbm_mcp_handle_tool(srv, "search_graph",
                                    "{\"project\":\"testproj\","
                                    "\"label\":\"Function\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    /* Project results must have source:"project" */
    ASSERT_NOT_NULL(strstr(resp, "\"source\":\"project\""));

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_search_dep_results_tagged_dependency) {
    /* Dep results must have source:"dependency", package, read_only */
    char tmp[256];
    cbm_mcp_server_t *srv = setup_proj_with_deps(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    /* Search dep nodes via project_pattern */
    char *raw = cbm_mcp_handle_tool(srv, "search_graph",
                                    "{\"project\":\"testproj\","
                                    "\"label\":\"Class\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    /* DataFrame is a dep node — should have source:dependency */
    if (strstr(resp, "DataFrame")) {
        ASSERT_NOT_NULL(strstr(resp, "\"source\":\"dependency\""));
        ASSERT_NOT_NULL(strstr(resp, "\"read_only\":true"));
        ASSERT_NOT_NULL(strstr(resp, "\"package\":\"pandas\""));
    }

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_search_response_has_session_project) {
    /* Every response must include session_project */
    char tmp[256];
    cbm_mcp_server_t *srv = setup_proj_with_deps(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    char *raw = cbm_mcp_handle_tool(srv, "search_graph",
                                    "{\"project\":\"testproj\","
                                    "\"label\":\"Function\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    ASSERT_NOT_NULL(strstr(resp, "\"session_project\":\"testproj\""));

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  INDEX STATUS: dep info in response
 * ══════════════════════════════════════════════════════════════════ */

TEST(test_index_status_shows_deps) {
    char tmp[256];
    cbm_mcp_server_t *srv = setup_proj_with_deps(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    char *raw = cbm_mcp_handle_tool(srv, "index_status",
                                    "{\"project\":\"testproj\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    /* Should include dependency info */
    ASSERT_TRUE(strstr(resp, "\"dependencies\"") != NULL ||
                strstr(resp, "\"dependency_count\"") != NULL);

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  TRACE/SNIPPET SOURCE TAGGING + CROSS-EDGES
 * ══════════════════════════════════════════════════════════════════ */

TEST(test_trace_results_have_source_field) {
    char tmp[256];
    cbm_mcp_server_t *srv = setup_dep_query_server(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    char *raw = cbm_mcp_handle_tool(srv, "trace_call_path",
                                    "{\"function_name\":\"process_data\","
                                    "\"project\":\"dep-query-test\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    if (strstr(resp, "callees") && strstr(resp, "source")) {
        ASSERT_NOT_NULL(strstr(resp, "\"source\":\"project\""));
    }

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_snippet_has_source_field) {
    char tmp[256];
    cbm_mcp_server_t *srv = setup_dep_query_server(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    char *raw = cbm_mcp_handle_tool(srv, "get_code_snippet",
                                    "{\"qualified_name\":\"dep-query-test.app.process_data\","
                                    "\"project\":\"dep-query-test\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    ASSERT_NOT_NULL(strstr(resp, "\"source\":\"project\""));

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_cross_edges_null_safety) {
    ASSERT_EQ(0, cbm_dep_link_cross_edges(NULL, "test"));
    ASSERT_EQ(0, cbm_dep_link_cross_edges(NULL, NULL));

    cbm_store_t *st = cbm_store_open_memory();
    ASSERT_NOT_NULL(st);
    ASSERT_EQ(0, cbm_dep_link_cross_edges(st, "nonexistent"));
    ASSERT_EQ(0, cbm_dep_link_cross_edges(st, ""));
    cbm_store_close(st);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  SUITE
 * ══════════════════════════════════════════════════════════════════ */

SUITE(depindex) {
    /* MCP tool registration and validation */
    RUN_TEST(tool_index_dependencies_listed);
    RUN_TEST(tool_index_dependencies_missing_project);
    RUN_TEST(tool_index_dependencies_missing_packages);

    /* AI grounding: core vs dependency disambiguation */
    RUN_TEST(search_graph_default_excludes_deps);
    RUN_TEST(search_graph_include_deps_marks_source);
    RUN_TEST(trace_call_path_marks_boundary);
    RUN_TEST(get_code_snippet_dep_shows_provenance);

    /* External node marking */
    RUN_TEST(build_def_props_no_external_when_null_ctx);

    /* QN prefixing */
    RUN_TEST(dep_qn_no_collision_with_project);

    /* Separate storage */
    RUN_TEST(dep_db_path_convention);

    /* Dependency discovery */
    RUN_TEST(dep_discover_skips_test_dirs);
    RUN_TEST(dep_discover_max_files_guard);

    /* Depindex helpers */
    RUN_TEST(test_parse_pkg_manager_valid);
    RUN_TEST(test_parse_pkg_manager_invalid);
    RUN_TEST(test_pkg_manager_str_roundtrip);
    RUN_TEST(test_dep_project_name_format);
    RUN_TEST(test_is_dep_project_with_session);
    RUN_TEST(test_is_dep_project_without_session);
    RUN_TEST(test_detect_ecosystem_python);
    RUN_TEST(test_detect_ecosystem_rust);
    RUN_TEST(test_detect_ecosystem_none);
    RUN_TEST(test_is_manifest_path);
    RUN_TEST(test_resolve_npm_node_modules);
    RUN_TEST(test_pipeline_set_project_name);
    RUN_TEST(test_dep_reindex_replaces);

    /* Result tagging */
    RUN_TEST(test_search_results_have_source_field);
    RUN_TEST(test_search_dep_results_tagged_dependency);
    RUN_TEST(test_search_response_has_session_project);

    /* Index status deps */
    RUN_TEST(test_index_status_shows_deps);

    /* Trace and snippet source tagging */
    RUN_TEST(test_trace_results_have_source_field);
    RUN_TEST(test_snippet_has_source_field);
    RUN_TEST(test_cross_edges_null_safety);
}
