/*
 * test_depindex.c — Tests for dependency/reference API indexing.
 *
 * Covers: package resolution, dependency discovery, external node marking,
 *         QN prefixing, separate storage, AI grounding safeguards.
 *
 * TDD: All tests written BEFORE implementation. They should fail (RED)
 * until the corresponding feature is implemented (GREEN).
 */
#include "../src/foundation/compat.h"
#include "../src/foundation/compat_fs.h"
#include "../src/foundation/constants.h"
#include "test_framework.h"
#include <cli/cli.h>
#include <mcp/mcp.h>
#include <store/store.h>
#include <depindex/depindex.h>
#include <yyjson/yyjson.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/stat.h>
#include <unistd.h>
#include "sqlite3.h"

/* ── Helpers ─────────────────────────────────────────────────── */

static char *extract_text_content_di(const char *mcp_result) {
    if (!mcp_result)
        return NULL;
    yyjson_doc *doc = yyjson_read(mcp_result, strlen(mcp_result), 0);
    if (!doc)
        return strdup(mcp_result);
    yyjson_val *root = yyjson_doc_get_root(doc);
    yyjson_val *content = yyjson_obj_get(root, "content");
    if (!content || !yyjson_is_arr(content)) {
        yyjson_doc_free(doc);
        return strdup(mcp_result);
    }
    yyjson_val *item = yyjson_arr_get(content, 0);
    if (!item) {
        yyjson_doc_free(doc);
        return strdup(mcp_result);
    }
    yyjson_val *text = yyjson_obj_get(item, "text");
    const char *str = yyjson_get_str(text);
    char *result = str ? strdup(str) : strdup(mcp_result);
    yyjson_doc_free(doc);
    return result;
}

/* Create a temp dir with a fake cargo project structure for testing. */
static int __attribute__((unused)) setup_cargo_fixture(char *tmp_dir, size_t tmp_sz) {
    snprintf(tmp_dir, tmp_sz, "/tmp/cbm_deptest_XXXXXX");
    if (!cbm_mkdtemp(tmp_dir))
        return -1;

    char proj_dir[512];
    snprintf(proj_dir, sizeof(proj_dir), "%s/project", tmp_dir);
    cbm_mkdir(proj_dir);

    /* Write a Cargo.lock with a serde entry */
    char lock_path[512];
    snprintf(lock_path, sizeof(lock_path), "%s/Cargo.lock", proj_dir);
    FILE *fp = fopen(lock_path, "w");
    if (!fp)
        return -1;
    fprintf(fp, "# This file is automatically @generated by Cargo.\n"
                "[[package]]\n"
                "name = \"my-project\"\n"
                "version = \"0.1.0\"\n\n"
                "[[package]]\n"
                "name = \"serde\"\n"
                "version = \"1.0.200\"\n"
                "source = \"registry+https://github.com/rust-lang/crates.io-index\"\n\n"
                "[[package]]\n"
                "name = \"tokio\"\n"
                "version = \"1.37.0\"\n"
                "source = \"registry+https://github.com/rust-lang/crates.io-index\"\n");
    fclose(fp);

    /* Write a simple src/main.rs */
    char src_dir[512];
    snprintf(src_dir, sizeof(src_dir), "%s/src", proj_dir);
    cbm_mkdir(src_dir);
    char main_path[512];
    snprintf(main_path, sizeof(main_path), "%s/main.rs", src_dir);
    fp = fopen(main_path, "w");
    if (!fp)
        return -1;
    fprintf(fp, "use serde::Serialize;\n\n"
                "fn main() {\n"
                "    println!(\"hello\");\n"
                "}\n");
    fclose(fp);

    return 0;
}

/* Create a temp dir with fake Python venv structure. */
static int __attribute__((unused)) setup_uv_fixture(char *tmp_dir, size_t tmp_sz) {
    snprintf(tmp_dir, tmp_sz, "/tmp/cbm_uvtest_XXXXXX");
    if (!cbm_mkdtemp(tmp_dir))
        return -1;

    char proj_dir[512];
    snprintf(proj_dir, sizeof(proj_dir), "%s/project", tmp_dir);
    cbm_mkdir(proj_dir);

    char pyproject_path[512];
    snprintf(pyproject_path, sizeof(pyproject_path), "%s/pyproject.toml", proj_dir);
    FILE *fp = fopen(pyproject_path, "w");
    if (!fp)
        return -1;
    fprintf(fp, "[project]\nname = \"fixture\"\ndependencies = [\"requests\"]\n");
    fclose(fp);

    /* Create .venv/lib/python3.12/site-packages/requests/ */
    char venv_path[512];
    snprintf(venv_path, sizeof(venv_path), "%s/.venv", proj_dir);
    cbm_mkdir(venv_path);
    snprintf(venv_path, sizeof(venv_path), "%s/.venv/lib", proj_dir);
    cbm_mkdir(venv_path);
    snprintf(venv_path, sizeof(venv_path), "%s/.venv/lib/python3.12", proj_dir);
    cbm_mkdir(venv_path);
    snprintf(venv_path, sizeof(venv_path), "%s/.venv/lib/python3.12/site-packages", proj_dir);
    cbm_mkdir(venv_path);
    snprintf(venv_path, sizeof(venv_path),
             "%s/.venv/lib/python3.12/site-packages/requests", proj_dir);
    cbm_mkdir(venv_path);

    /* Write a simple __init__.py */
    char init_path[512];
    snprintf(init_path, sizeof(init_path), "%s/__init__.py", venv_path);
    fp = fopen(init_path, "w");
    if (!fp)
        return -1;
    fprintf(fp, "\"\"\"Requests library.\"\"\"\n\n"
                "def get(url, **kwargs):\n"
                "    \"\"\"Send a GET request.\"\"\"\n"
                "    pass\n\n"
                "def post(url, data=None, **kwargs):\n"
                "    \"\"\"Send a POST request.\"\"\"\n"
                "    pass\n");
    fclose(fp);

    return 0;
}

static void cleanup_fixture_dir(const char *tmp_dir) {
    /* Best-effort recursive cleanup via system command */
    char cmd[512];
    snprintf(cmd, sizeof(cmd), "rm -rf '%s' 2>/dev/null", tmp_dir);
    (void)system(cmd);
}

/* Create an MCP server with a project indexed, for testing query integration. */
static cbm_mcp_server_t *setup_dep_query_server(char *tmp_dir, size_t tmp_sz) {
    snprintf(tmp_dir, tmp_sz, "/tmp/cbm_depquery_XXXXXX");
    if (!cbm_mkdtemp(tmp_dir))
        return NULL;

    char proj_dir[512];
    snprintf(proj_dir, sizeof(proj_dir), "%s/project", tmp_dir);
    cbm_mkdir(proj_dir);

    /* Write source file */
    char src_path[512];
    snprintf(src_path, sizeof(src_path), "%s/app.py", proj_dir);
    FILE *fp = fopen(src_path, "w");
    if (!fp)
        return NULL;
    fprintf(fp, "import pandas as pd\n\n"
                "def process_data():\n"
                "    df = pd.DataFrame()\n"
                "    return df\n");
    fclose(fp);

    cbm_mcp_server_t *srv = cbm_mcp_server_new(NULL);
    if (!srv)
        return NULL;

    cbm_store_t *st = cbm_mcp_server_store(srv);
    if (!st) {
        cbm_mcp_server_free(srv);
        return NULL;
    }

    const char *proj_name = "dep-query-test";
    cbm_mcp_server_set_project(srv, proj_name);
    cbm_store_upsert_project(st, proj_name, proj_dir);

    /* Create project node */
    cbm_node_t n_proc = {0};
    n_proc.project = proj_name;
    n_proc.label = "Function";
    n_proc.name = "process_data";
    n_proc.qualified_name = "dep-query-test.app.process_data";
    n_proc.file_path = "app.py";
    n_proc.start_line = 3;
    n_proc.end_line = 5;
    n_proc.properties_json = "{\"is_exported\":true}";
    cbm_store_upsert_node(st, &n_proc);

    return srv;
}

static int count_fts_matches(cbm_store_t *st, const char *project, const char *query) {
    sqlite3 *db = cbm_store_get_db(st);
    if (!db) return -1;
    sqlite3_stmt *stmt = NULL;
    const char *sql =
        "SELECT COUNT(*) "
        "FROM nodes_fts f JOIN nodes n ON n.id = f.rowid "
        "WHERE nodes_fts MATCH ?1 AND n.project = ?2";
    if (sqlite3_prepare_v2(db, sql, -1, &stmt, NULL) != SQLITE_OK) {
        return -1;
    }
    sqlite3_bind_text(stmt, 1, query, -1, SQLITE_TRANSIENT);
    sqlite3_bind_text(stmt, 2, project, -1, SQLITE_TRANSIENT);
    int count = -1;
    if (sqlite3_step(stmt) == SQLITE_ROW) {
        count = sqlite3_column_int(stmt, 0);
    }
    sqlite3_finalize(stmt);
    return count;
}

/* ══════════════════════════════════════════════════════════════════
 *  PACKAGE RESOLUTION (requires depindex.h — will fail until implemented)
 * ══════════════════════════════════════════════════════════════════ */

/*
 * NOTE: Package resolution tests depend on src/depindex/depindex.h which
 * does not exist yet. These tests will cause compilation errors until
 * Feature 2 implementation begins. For the RED phase, we test only the
 * MCP-level behavior via the server handle interface.
 */

/* ══════════════════════════════════════════════════════════════════
 *  MCP TOOL: index_dependencies (via server handle)
 * ══════════════════════════════════════════════════════════════════ */

TEST(tool_index_dependencies_listed) {
    char *json = cbm_mcp_tools_list(NULL);
    ASSERT_NOT_NULL(json);
    /* §4b: in streamlined mode (NULL srv), index_dependencies is hidden.
     * The default surface includes search_graph (split tool). */
    ASSERT_NOT_NULL(strstr(json, "search_graph"));
    free(json);
    PASS();
}

TEST(tool_index_dependencies_missing_project) {
    cbm_mcp_server_t *srv = cbm_mcp_server_new(NULL);

    char *resp = cbm_mcp_server_handle(
        srv, "{\"jsonrpc\":\"2.0\",\"id\":50,\"method\":\"tools/call\","
             "\"params\":{\"name\":\"index_dependencies\","
             "\"arguments\":{\"package_manager\":\"cargo\"}}}");
    ASSERT_NOT_NULL(resp);
    /* Should require project parameter */
    ASSERT_NOT_NULL(strstr(resp, "required"));
    free(resp);

    cbm_mcp_server_free(srv);
    PASS();
}

TEST(tool_index_dependencies_missing_packages) {
    cbm_mcp_server_t *srv = cbm_mcp_server_new(NULL);

    /* packages[] is now required */
    char *resp = cbm_mcp_server_handle(
        srv, "{\"jsonrpc\":\"2.0\",\"id\":51,\"method\":\"tools/call\","
             "\"params\":{\"name\":\"index_dependencies\","
             "\"arguments\":{\"project\":\"test\"}}}");
    ASSERT_NOT_NULL(resp);
    ASSERT_NOT_NULL(strstr(resp, "required"));
    free(resp);

    cbm_mcp_server_free(srv);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  AI GROUNDING: DEFAULT QUERY EXCLUDES DEPENDENCIES
 * ══════════════════════════════════════════════════════════════════ */

TEST(search_graph_default_excludes_deps) {
    char tmp[256];
    cbm_mcp_server_t *srv = setup_dep_query_server(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    /* Default search_graph (no include_dependencies) should only return
     * project code — NEVER dependency code. This is the MOST IMPORTANT
     * test for AI grounding. */
    char *raw = cbm_mcp_handle_tool(srv, "search_graph",
                                    "{\"project\":\"dep-query-test\","
                                    "\"label\":\"Function\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    /* Should find process_data (project code) */
    ASSERT_NOT_NULL(strstr(resp, "process_data"));
    /* Should NOT find any dep.* qualified names */
    ASSERT_NULL(strstr(resp, "\"dep."));
    /* Should NOT find external:true markers */
    ASSERT_NULL(strstr(resp, "\"external\":true"));

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(search_graph_include_deps_marks_source) {
    char tmp[256];
    cbm_mcp_server_t *srv = setup_dep_query_server(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    /* With include_dependencies=true, results should have source field.
     * format:"json" opts into the legacy JSON shape carrying per-result
     * source tags (the TOON default has no source column). */
    char *raw = cbm_mcp_handle_tool(srv, "search_graph",
                                    "{\"project\":\"dep-query-test\","
                                    "\"label\":\"Function\","
                                    "\"include_dependencies\":true,"
                                    "\"format\":\"json\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    /* Project results should have source:"project" */
    ASSERT_NOT_NULL(strstr(resp, "\"source\":\"project\""));

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(trace_path_dependency_graph_uses_supported_schema) {
    char tmp[256];
    cbm_mcp_server_t *srv = setup_dep_query_server(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    /* Dependency nodes share the project graph and trace_path follows its
     * selected edge set directly; it has never advertised a separate
     * include_dependencies switch. Verify the supported call remains safe. */
    char *raw = cbm_mcp_handle_tool(srv, "trace_path",
                                    "{\"function_name\":\"process_data\","
                                    "\"project\":\"dep-query-test\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    /* Response should exist (even if no deps indexed yet, should not crash) */
    ASSERT_NOT_NULL(strstr(resp, "process_data"));

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(get_code_snippet_dep_shows_provenance) {
    char tmp[256];
    cbm_mcp_server_t *srv = setup_dep_query_server(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    /* Requesting a dep symbol should show package provenance */
    char *raw = cbm_mcp_handle_tool(srv, "get_code_snippet",
                                    "{\"qualified_name\":\"dep.uv.pandas.DataFrame\","
                                    "\"project\":\"dep-query-test\","
                                    "\"include_dependencies\":true}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);
    /* Without deps indexed, should return not found — that's fine.
     * The key test is that include_dependencies doesn't crash. */

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  EXTERNAL NODE MARKING
 * ══════════════════════════════════════════════════════════════════ */

TEST(build_def_props_no_external_when_null_ctx) {
    /* Normal indexing (dep_ctx=NULL) should NOT add external metadata.
     * We test this indirectly: index a project, check properties. */
    cbm_mcp_server_t *srv = cbm_mcp_server_new(NULL);
    cbm_store_t *st = cbm_mcp_server_store(srv);

    cbm_node_t n = {0};
    n.project = "test";
    n.label = "Function";
    n.name = "my_func";
    n.qualified_name = "test.my_func";
    n.file_path = "test.py";
    n.start_line = 1;
    n.end_line = 3;
    n.properties_json = "{\"is_exported\":true}";
    cbm_store_upsert_node(st, &n);

    /* Properties should NOT contain "external" */
    ASSERT_NULL(strstr(n.properties_json, "external"));

    cbm_mcp_server_free(srv);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  QN PREFIXING
 * ══════════════════════════════════════════════════════════════════ */

TEST(dep_qn_no_collision_with_project) {
    /* If project has module "pandas" and dep has package "pandas",
     * their QNs must not collide.
     * Project: "my-project.pandas.helper"
     * Dep:     "dep.uv.pandas.DataFrame"
     * These are clearly different prefixes. */
    const char *proj_qn = "my-project.pandas.helper";
    const char *dep_qn = "dep.uv.pandas.DataFrame";
    ASSERT_TRUE(strncmp(proj_qn, dep_qn, 4) != 0); /* "my-p" != "dep." */
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  SEPARATE STORAGE
 * ══════════════════════════════════════════════════════════════════ */

TEST(dep_db_path_convention) {
    /* Verify the naming convention: {project}_deps.db */
    const char *project = "my-project";
    char expected[256];
    snprintf(expected, sizeof(expected), "%s_deps.db", project);
    ASSERT_STR_EQ(expected, "my-project_deps.db");
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  DEPENDENCY DISCOVERY (file filtering)
 * ══════════════════════════════════════════════════════════════════ */

TEST(dep_discover_skips_test_dirs) {
    char tmp[256];
    snprintf(tmp, sizeof(tmp), "/tmp/cbm_disc_test_XXXXXX");
    if (!cbm_mkdtemp(tmp)) {
        SKIP("Could not create temp dir");
    }

    /* Create src/lib.rs and tests/test_foo.rs */
    char src_dir[512], test_dir[512];
    snprintf(src_dir, sizeof(src_dir), "%s/src", tmp);
    cbm_mkdir(src_dir);
    snprintf(test_dir, sizeof(test_dir), "%s/tests", tmp);
    cbm_mkdir(test_dir);

    char path[512];
    snprintf(path, sizeof(path), "%s/lib.rs", src_dir);
    FILE *fp = fopen(path, "w");
    if (fp) { fprintf(fp, "pub fn hello() {}\n"); fclose(fp); }

    snprintf(path, sizeof(path), "%s/test_foo.rs", test_dir);
    fp = fopen(path, "w");
    if (fp) { fprintf(fp, "#[test]\nfn test_foo() {}\n"); fclose(fp); }

    /* When dependency discovery is implemented, it should skip tests/ */
    /* For now, just verify the fixture was created correctly */
    snprintf(path, sizeof(path), "%s/lib.rs", src_dir);
    fp = fopen(path, "r");
    ASSERT_NOT_NULL(fp);
    fclose(fp);

    snprintf(path, sizeof(path), "%s/test_foo.rs", test_dir);
    fp = fopen(path, "r");
    ASSERT_NOT_NULL(fp);
    fclose(fp);

    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(dep_discover_max_files_guard) {
    /* Verify concept: if a package has >1000 files, we cap at 1000.
     * We won't create 1000 files in the test — just verify the constant. */
    int max_files_default = 1000;
    ASSERT_EQ(max_files_default, 1000);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  FIXTURE: Project + dep nodes in same db for integration tests
 * ══════════════════════════════════════════════════════════════════ */

/* Create an MCP server with project AND dep nodes indexed. */
static cbm_mcp_server_t *setup_proj_with_deps(char *tmp_dir, size_t tmp_sz) {
    snprintf(tmp_dir, tmp_sz, "/tmp/cbm_depfull_XXXXXX");
    if (!cbm_mkdtemp(tmp_dir))
        return NULL;

    char proj_dir[512];
    snprintf(proj_dir, sizeof(proj_dir), "%s/project", tmp_dir);
    cbm_mkdir(proj_dir);

    /* Write a source file */
    char src_path[512];
    snprintf(src_path, sizeof(src_path), "%s/app.py", proj_dir);
    FILE *fp = fopen(src_path, "w");
    if (!fp) return NULL;
    fprintf(fp, "import pandas as pd\ndef process_data():\n    return pd.DataFrame()\n");
    fclose(fp);

    cbm_mcp_server_t *srv = cbm_mcp_server_new(NULL);
    if (!srv) return NULL;
    cbm_store_t *st = cbm_mcp_server_store(srv);
    if (!st) { cbm_mcp_server_free(srv); return NULL; }

    const char *proj_name = "testproj";
    cbm_mcp_server_set_project(srv, proj_name);
    cbm_mcp_server_set_session_project(srv, proj_name);
    cbm_store_upsert_project(st, proj_name, proj_dir);

    /* Project node */
    cbm_node_t n1 = {0};
    n1.project = proj_name;
    n1.label = "Function";
    n1.name = "process_data";
    n1.qualified_name = "testproj.app.process_data";
    n1.file_path = "app.py";
    n1.start_line = 2;
    n1.end_line = 3;
    n1.properties_json = "{\"is_exported\":true}";
    cbm_store_upsert_node(st, &n1);

    /* Dep nodes */
    cbm_store_upsert_project(st, "testproj.dep.pandas", "/tmp/pandas");

    cbm_node_t n_df = {0};
    n_df.project = "testproj.dep.pandas";
    n_df.label = "Class";
    n_df.name = "DataFrame";
    n_df.qualified_name = "testproj.dep.pandas.DataFrame";
    n_df.file_path = "pandas/core/frame.py";
    n_df.start_line = 100;
    n_df.end_line = 500;
    n_df.properties_json = "{\"is_exported\":true}";
    cbm_store_upsert_node(st, &n_df);

    cbm_node_t n_read = {0};
    n_read.project = "testproj.dep.pandas";
    n_read.label = "Function";
    n_read.name = "read_csv";
    n_read.qualified_name = "testproj.dep.pandas.read_csv";
    n_read.file_path = "pandas/io/parsers.py";
    n_read.start_line = 50;
    n_read.end_line = 80;
    n_read.properties_json = "{\"is_exported\":true}";
    cbm_store_upsert_node(st, &n_read);

    return srv;
}

/* ══════════════════════════════════════════════════════════════════
 *  DEPINDEX HELPER UNIT TESTS
 * ══════════════════════════════════════════════════════════════════ */

#include <depindex/depindex.h>
#include <pipeline/pipeline.h>

TEST(test_parse_pkg_manager_valid) {
    ASSERT_EQ(cbm_parse_pkg_manager("uv"), CBM_PKG_UV);
    ASSERT_EQ(cbm_parse_pkg_manager("pip"), CBM_PKG_UV);
    ASSERT_EQ(cbm_parse_pkg_manager("cargo"), CBM_PKG_CARGO);
    ASSERT_EQ(cbm_parse_pkg_manager("npm"), CBM_PKG_NPM);
    ASSERT_EQ(cbm_parse_pkg_manager("bun"), CBM_PKG_BUN);
    ASSERT_EQ(cbm_parse_pkg_manager("custom"), CBM_PKG_CUSTOM);
    PASS();
}

TEST(test_parse_pkg_manager_invalid) {
    ASSERT_EQ(cbm_parse_pkg_manager("nonexistent"), CBM_PKG_COUNT);
    ASSERT_EQ(cbm_parse_pkg_manager(NULL), CBM_PKG_COUNT);
    ASSERT_EQ(cbm_parse_pkg_manager(""), CBM_PKG_COUNT);
    PASS();
}

TEST(test_pkg_manager_str_roundtrip) {
    ASSERT_STR_EQ(cbm_pkg_manager_str(CBM_PKG_UV), "uv");
    ASSERT_STR_EQ(cbm_pkg_manager_str(CBM_PKG_CARGO), "cargo");
    ASSERT_STR_EQ(cbm_pkg_manager_str(CBM_PKG_NPM), "npm");
    ASSERT_STR_EQ(cbm_pkg_manager_str(CBM_PKG_COUNT), "unknown");
    PASS();
}

TEST(test_dep_project_name_format) {
    char *name = cbm_dep_project_name("myapp", "pandas");
    ASSERT_NOT_NULL(name);
    ASSERT_STR_EQ(name, "myapp.dep.pandas");
    free(name);

    name = cbm_dep_project_name("myapp", "serde");
    ASSERT_NOT_NULL(name);
    ASSERT_STR_EQ(name, "myapp.dep.serde");
    free(name);

    /* NULL inputs */
    ASSERT_NULL(cbm_dep_project_name(NULL, "pandas"));
    ASSERT_NULL(cbm_dep_project_name("myapp", NULL));
    PASS();
}

TEST(test_is_dep_project_with_session) {
    /* With session context — precise prefix check first, then generic .dep. fallback */
    ASSERT_TRUE(cbm_is_dep_project("myapp.dep.pandas", "myapp"));
    ASSERT_TRUE(cbm_is_dep_project("myapp.dep.serde", "myapp"));
    ASSERT_FALSE(cbm_is_dep_project("myapp", "myapp"));
    /* Cross-project deps: otherapp.dep.pandas contains ".dep." → IS a dep.
     * This is correct: when querying across projects, dep nodes from any project
     * should be tagged as dependencies for AI grounding (read_only, source tagging). */
    ASSERT_TRUE(cbm_is_dep_project("otherapp.dep.pandas", "myapp"));
    ASSERT_FALSE(cbm_is_dep_project(NULL, "myapp"));
    PASS();
}

TEST(test_is_dep_project_without_session) {
    /* Without session context — fallback strstr check */
    ASSERT_TRUE(cbm_is_dep_project("myapp.dep.pandas", NULL));
    ASSERT_TRUE(cbm_is_dep_project("dep.cargo.serde", NULL));
    ASSERT_FALSE(cbm_is_dep_project("myapp", NULL));
    ASSERT_FALSE(cbm_is_dep_project("deputy", NULL));
    PASS();
}

TEST(test_detect_ecosystem_python) {
    char tmp[256];
    snprintf(tmp, sizeof(tmp), "/tmp/cbm_eco_py_XXXXXX");
    if (!cbm_mkdtemp(tmp)) { SKIP("Could not create temp dir"); }
    char path[512];
    snprintf(path, sizeof(path), "%s/pyproject.toml", tmp);
    FILE *fp = fopen(path, "w");
    if (fp) { fprintf(fp, "[project]\nname = \"test\"\n"); fclose(fp); }
    ASSERT_EQ(cbm_detect_ecosystem(tmp), CBM_PKG_UV);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_detect_ecosystem_rust) {
    char tmp[256];
    snprintf(tmp, sizeof(tmp), "/tmp/cbm_eco_rs_XXXXXX");
    if (!cbm_mkdtemp(tmp)) { SKIP("Could not create temp dir"); }
    char path[512];
    snprintf(path, sizeof(path), "%s/Cargo.toml", tmp);
    FILE *fp = fopen(path, "w");
    if (fp) { fprintf(fp, "[package]\nname = \"test\"\n"); fclose(fp); }
    ASSERT_EQ(cbm_detect_ecosystem(tmp), CBM_PKG_CARGO);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_detect_ecosystem_none) {
    char tmp[256];
    snprintf(tmp, sizeof(tmp), "/tmp/cbm_eco_none_XXXXXX");
    if (!cbm_mkdtemp(tmp)) { SKIP("Could not create temp dir"); }
    ASSERT_EQ(cbm_detect_ecosystem(tmp), CBM_PKG_COUNT);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_is_manifest_path) {
    ASSERT_TRUE(cbm_is_manifest_path("src/Cargo.toml"));
    ASSERT_TRUE(cbm_is_manifest_path("/Users/x/myapp/pyproject.toml"));
    ASSERT_TRUE(cbm_is_manifest_path("package.json"));
    ASSERT_FALSE(cbm_is_manifest_path("src/main.rs"));
    ASSERT_FALSE(cbm_is_manifest_path(NULL));
    PASS();
}

TEST(test_resolve_npm_node_modules) {
    char tmp[256];
    snprintf(tmp, sizeof(tmp), "/tmp/cbm_resolve_npm_XXXXXX");
    if (!cbm_mkdtemp(tmp)) { SKIP("Could not create temp dir"); }

    /* Create node_modules/react/ with package.json */
    char nm[512];
    snprintf(nm, sizeof(nm), "%s/node_modules", tmp);
    cbm_mkdir(nm);
    snprintf(nm, sizeof(nm), "%s/node_modules/react", tmp);
    cbm_mkdir(nm);
    char pj[512];
    snprintf(pj, sizeof(pj), "%s/package.json", nm);
    FILE *fp = fopen(pj, "w");
    if (fp) { fprintf(fp, "{\"name\":\"react\",\"version\":\"18.2.0\"}\n"); fclose(fp); }

    cbm_dep_resolved_t out = {0};
    ASSERT_EQ(cbm_resolve_pkg_source(CBM_PKG_NPM, "react", tmp, &out), 0);
    ASSERT_NOT_NULL(out.path);
    ASSERT_NOT_NULL(strstr(out.path, "node_modules/react"));
    cbm_dep_resolved_free(&out);

    /* Non-existent package */
    cbm_dep_resolved_t out2 = {0};
    ASSERT_EQ(cbm_resolve_pkg_source(CBM_PKG_NPM, "nonexistent", tmp, &out2), -1);

    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_auto_index_npm_reads_actual_package_json_shape) {
    char tmp[CBM_SZ_256];
    snprintf(tmp, sizeof(tmp), "%s/cbm_npm_auto_XXXXXX", cbm_tmpdir());
    ASSERT_NOT_NULL(cbm_mkdtemp(tmp));

    char dep_dir[CBM_SZ_1K];
    snprintf(dep_dir, sizeof(dep_dir), "%s/node_modules/cbmbenchdep", tmp);
    ASSERT_TRUE(cbm_mkdir_p(dep_dir, 0700));

    char path[CBM_SZ_1K];
    snprintf(path, sizeof(path), "%s/package.json", tmp);
    FILE *fp = cbm_fopen(path, "wb");
    ASSERT_NOT_NULL(fp);
    ASSERT_GT(fprintf(fp, "{\"name\":\"fixture\",\"dependencies\":{\"cbmbenchdep\":"
                          "\"1.0.0\"}}\n"),
              0);
    ASSERT_EQ(fclose(fp), 0);

    snprintf(path, sizeof(path), "%s/index.js", dep_dir);
    fp = cbm_fopen(path, "wb");
    ASSERT_NOT_NULL(fp);
    ASSERT_GT(fprintf(fp, "export function canonicalDependencyAPI(value) { return value; }\n"), 0);
    ASSERT_EQ(fclose(fp), 0);

    cbm_store_t *store = cbm_store_open_memory();
    ASSERT_NOT_NULL(store);
    const char *project = "npm-auto-fixture";
    ASSERT_EQ(cbm_store_upsert_project(store, project, tmp), CBM_STORE_OK);

    /* This is the qualified-name shape emitted by the JSON extractor: the
     * package name is not nested below a `.dependencies.` QN segment. */
    cbm_node_t package_node = {0};
    package_node.project = project;
    package_node.label = "Variable";
    package_node.name = "cbmbenchdep";
    package_node.qualified_name = "npm-auto-fixture.package.cbmbenchdep";
    package_node.file_path = "package.json";
    package_node.properties_json = "{}";
    ASSERT_GT(cbm_store_upsert_node(store, &package_node), 0);

    ASSERT_EQ(cbm_dep_auto_index(project, tmp, store, 1, NULL), 1);
    ASSERT_GT(cbm_store_count_nodes(store, "npm-auto-fixture.dep.cbmbenchdep"), 0);

    cbm_store_close(store);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_discover_vendored_deps_unlimited_uses_actual_capacity) {
    char tmp[CBM_SZ_256];
    snprintf(tmp, sizeof(tmp), "%s/cbm_vendor_unlimited_XXXXXX", cbm_tmpdir());
    ASSERT_NOT_NULL(cbm_mkdtemp(tmp));

    char dep_a[CBM_SZ_1K];
    char dep_b[CBM_SZ_1K];
    snprintf(dep_a, sizeof(dep_a), "%s/vendor/alpha", tmp);
    snprintf(dep_b, sizeof(dep_b), "%s/vendor/beta", tmp);
    ASSERT_TRUE(cbm_mkdir_p(dep_a, 0700));
    ASSERT_TRUE(cbm_mkdir_p(dep_b, 0700));

    cbm_store_t *store = cbm_store_open_memory();
    ASSERT_NOT_NULL(store);
    ASSERT_EQ(cbm_store_upsert_project(store, "vendor-unlimited", tmp), CBM_STORE_OK);

    cbm_dep_discovered_t *deps = NULL;
    int dep_count = 0;
    ASSERT_EQ(cbm_discover_installed_deps(CBM_PKG_MAKE, tmp, store,
                                          "vendor-unlimited", &deps, &dep_count,
                                          INT_MAX),
              0);
    ASSERT_EQ(dep_count, 2);
    cbm_dep_discovered_free(deps, dep_count);
    cbm_store_close(store);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_discover_manifest_deps_unlimited_saturates_query_limit) {
    char tmp[CBM_SZ_256];
    ASSERT_EQ(setup_uv_fixture(tmp, sizeof(tmp)), 0);

    char proj_dir[CBM_SZ_1K];
    int n = snprintf(proj_dir, sizeof(proj_dir), "%s/project", tmp);
    ASSERT(n > 0 && (size_t)n < sizeof(proj_dir));

    cbm_store_t *store = cbm_store_open_memory();
    ASSERT_NOT_NULL(store);
    const char *project = "manifest-unlimited";
    ASSERT_EQ(cbm_store_upsert_project(store, project, proj_dir), CBM_STORE_OK);

    cbm_node_t dep_manifest = {0};
    dep_manifest.project = project;
    dep_manifest.label = "Variable";
    dep_manifest.name = "requests";
    dep_manifest.qualified_name = "manifest-unlimited.pyproject.dependencies.requests";
    dep_manifest.file_path = "pyproject.toml";
    dep_manifest.properties_json = "{}";
    ASSERT_GT(cbm_store_upsert_node(store, &dep_manifest), 0);

    cbm_dep_discovered_t *deps = NULL;
    int dep_count = 0;
    ASSERT_EQ(cbm_discover_installed_deps(CBM_PKG_UV, proj_dir, store, project,
                                          &deps, &dep_count, INT_MAX),
              0);
    ASSERT_EQ(dep_count, 1);
    ASSERT_STR_EQ(deps[0].package, "requests");
    cbm_dep_discovered_free(deps, dep_count);
    cbm_store_close(store);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_pipeline_set_project_name) {
    cbm_pipeline_t *p = cbm_pipeline_new("/tmp", NULL, CBM_MODE_FULL);
    ASSERT_NOT_NULL(p);
    const char *orig = cbm_pipeline_project_name(p);
    ASSERT_NOT_NULL(orig);
    /* Set custom name */
    cbm_pipeline_set_project_name(p, "myapp.dep.pandas");
    ASSERT_STR_EQ(cbm_pipeline_project_name(p), "myapp.dep.pandas");
    cbm_pipeline_free(p);
    PASS();
}

TEST(test_dep_reindex_replaces) {
    /* Verify upsert replaces old nodes for same QN, not duplicates. */
    cbm_store_t *store = cbm_store_open_memory();
    ASSERT_NOT_NULL(store);

    /* Must register project first (foreign key) */
    cbm_store_upsert_project(store, "test.dep.pandas", "/tmp/pandas");

    cbm_node_t n1 = {0};
    n1.project = "test.dep.pandas";
    n1.label = "Function";
    n1.name = "old_func";
    n1.qualified_name = "test.dep.pandas.old_func";
    n1.file_path = "pandas/__init__.py";
    n1.start_line = 1;
    n1.end_line = 3;
    n1.properties_json = "{}";
    cbm_store_upsert_node(store, &n1);

    int count1 = cbm_store_count_nodes(store, "test.dep.pandas");
    ASSERT_EQ(count1, 1);

    /* Upsert with same QN — should not duplicate */
    cbm_store_upsert_node(store, &n1);
    int count2 = cbm_store_count_nodes(store, "test.dep.pandas");
    ASSERT_EQ(count2, 1);

    cbm_store_close(store);
    PASS();
}

TEST(test_auto_index_deps_refreshes_nodes_fts) {
    char tmp[256];
    ASSERT_EQ(setup_uv_fixture(tmp, sizeof(tmp)), 0);

    char proj_dir[512];
    int n = snprintf(proj_dir, sizeof(proj_dir), "%s/project", tmp);
    ASSERT(n > 0 && (size_t)n < sizeof(proj_dir));

    cbm_store_t *store = cbm_store_open_memory();
    ASSERT_NOT_NULL(store);

    const char *project = "dep-fts-test";
    ASSERT_EQ(cbm_store_upsert_project(store, project, proj_dir), CBM_STORE_OK);

    cbm_node_t dep_manifest = {0};
    dep_manifest.project = project;
    dep_manifest.label = "Variable";
    dep_manifest.name = "requests";
    dep_manifest.qualified_name = "dep-fts-test.pyproject.dependencies.requests";
    dep_manifest.file_path = "pyproject.toml";
    dep_manifest.start_line = 3;
    dep_manifest.end_line = 3;
    dep_manifest.properties_json = "{}";
    ASSERT_GT(cbm_store_upsert_node(store, &dep_manifest), 0);

    ASSERT_EQ(cbm_dep_auto_index(project, proj_dir, store, 1, NULL), 1);
    ASSERT_GT(cbm_store_count_nodes(store, "dep-fts-test.dep.requests"), 0);
    ASSERT_GT(count_fts_matches(store, "dep-fts-test.dep.requests", "get"), 0);

    cbm_file_hash_t *hashes = NULL;
    int hash_count = 0;
    ASSERT_EQ(cbm_store_get_file_hashes(store, "dep-fts-test.dep.requests", &hashes, &hash_count),
              CBM_STORE_OK);
    ASSERT_EQ(hash_count, 1);
    cbm_store_free_file_hashes(hashes, hash_count);

    cbm_file_state_t state = {0};
    ASSERT_EQ(cbm_store_get_file_state(store, "dep-fts-test.dep.requests", "__init__.py", &state),
              CBM_STORE_OK);
    ASSERT_NOT_NULL(state.pass_fingerprint);
    cbm_store_file_state_free_fields(&state);

    ASSERT_EQ(cbm_dep_auto_index(project, proj_dir, store, 1, NULL), 0);
    ASSERT_GT(count_fts_matches(store, "dep-fts-test.dep.requests", "get"), 0);

    char init_path[512];
    n = snprintf(init_path, sizeof(init_path),
                 "%s/.venv/lib/python3.12/site-packages/requests/__init__.py", proj_dir);
    ASSERT(n > 0 && (size_t)n < sizeof(init_path));
    FILE *fp = fopen(init_path, "w");
    ASSERT_NOT_NULL(fp);
    fprintf(fp, "def put(url, **kwargs):\n    return url\n");
    fclose(fp);

    ASSERT_EQ(cbm_dep_auto_index(project, proj_dir, store, 1, NULL), 1);
    /* Removed defs must leave the FTS index after the refresh. "post" is gone
     * and is not a Python builtin, so it must have zero matches. "get" is no
     * longer a def either, but every Python file mints the synthetic builtin
     * nodes from internal/cbm/lsp/py_builtins.c — including builtins.dict.get
     * (name "get", file "<python-builtins>") — so exactly ONE live "get" row
     * remains: the builtin, not the deleted requests.get definition. */
    ASSERT_EQ(count_fts_matches(store, "dep-fts-test.dep.requests", "post"), 0);
    ASSERT_EQ(count_fts_matches(store, "dep-fts-test.dep.requests", "get"), 1);
    ASSERT_GT(count_fts_matches(store, "dep-fts-test.dep.requests", "put"), 0);

    cbm_store_close(store);
    cleanup_fixture_dir(tmp);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  RESULT TAGGING: source field on all search results
 * ══════════════════════════════════════════════════════════════════ */

TEST(test_search_results_have_source_field) {
    /* ALL search results must have source:"project" or source:"dependency" */
    char tmp[256];
    cbm_mcp_server_t *srv = setup_proj_with_deps(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    /* Search with no project filter — should return both project + dep nodes.
     * format:"json" opts into the legacy JSON shape with source tags. */
    char *raw = cbm_mcp_handle_tool(srv, "search_graph",
                                    "{\"project\":\"testproj\","
                                    "\"label\":\"Function\",\"format\":\"json\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    /* Project results must have source:"project" */
    ASSERT_NOT_NULL(strstr(resp, "\"source\":\"project\""));

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_search_dep_results_tagged_dependency) {
    /* Dep results must have source:"dependency", package, read_only */
    char tmp[256];
    cbm_mcp_server_t *srv = setup_proj_with_deps(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    /* Search dep nodes via project_pattern (format:"json" for source tags) */
    char *raw = cbm_mcp_handle_tool(srv, "search_graph",
                                    "{\"project\":\"testproj\","
                                    "\"label\":\"Class\",\"format\":\"json\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    /* DataFrame is a dep node — should have source:dependency */
    if (strstr(resp, "DataFrame")) {
        ASSERT_NOT_NULL(strstr(resp, "\"source\":\"dependency\""));
        ASSERT_NOT_NULL(strstr(resp, "\"read_only\":true"));
        ASSERT_NOT_NULL(strstr(resp, "\"package\":\"pandas\""));
    }

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_search_response_has_session_project) {
    /* Every response must include session_project */
    char tmp[256];
    cbm_mcp_server_t *srv = setup_proj_with_deps(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    char *raw = cbm_mcp_handle_tool(srv, "search_graph",
                                    "{\"project\":\"testproj\","
                                    "\"label\":\"Function\",\"format\":\"json\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    ASSERT_NOT_NULL(strstr(resp, "\"session_project\":\"testproj\""));

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  INDEX STATUS: dep info in response
 * ══════════════════════════════════════════════════════════════════ */

TEST(test_index_status_shows_deps) {
    char tmp[256];
    cbm_mcp_server_t *srv = setup_proj_with_deps(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    char *raw = cbm_mcp_handle_tool(srv, "index_status",
                                    "{\"project\":\"testproj\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    /* Should include dependency info */
    ASSERT_TRUE(strstr(resp, "\"dependencies\"") != NULL ||
                strstr(resp, "\"dependency_count\"") != NULL);

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  TRACE/SNIPPET SOURCE TAGGING + CROSS-EDGES
 * ══════════════════════════════════════════════════════════════════ */

TEST(test_trace_results_have_source_field) {
    char tmp[256];
    cbm_mcp_server_t *srv = setup_dep_query_server(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    char *raw = cbm_mcp_handle_tool(srv, "trace_path",
                                    "{\"function_name\":\"process_data\","
                                    "\"project\":\"dep-query-test\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    if (strstr(resp, "callees") && strstr(resp, "source")) {
        ASSERT_NOT_NULL(strstr(resp, "\"source\":\"project\""));
    }

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_snippet_has_source_origin_field) {
    char tmp[256];
    cbm_mcp_server_t *srv = setup_dep_query_server(tmp, sizeof(tmp));
    ASSERT_NOT_NULL(srv);

    char *raw = cbm_mcp_handle_tool(srv, "get_code_snippet",
                                    "{\"qualified_name\":\"dep-query-test.app.process_data\","
                                    "\"project\":\"dep-query-test\"}");
    char *resp = extract_text_content_di(raw);
    free(raw);
    ASSERT_NOT_NULL(resp);

    ASSERT_NOT_NULL(strstr(resp, "\"source_origin\":\"project\""));

    free(resp);
    cbm_mcp_server_free(srv);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_cross_edges_null_safety) {
    ASSERT_EQ(0, cbm_dep_link_cross_edges(NULL, "test"));
    ASSERT_EQ(0, cbm_dep_link_cross_edges(NULL, NULL));

    cbm_store_t *st = cbm_store_open_memory();
    ASSERT_NOT_NULL(st);
    ASSERT_EQ(0, cbm_dep_link_cross_edges(st, "nonexistent"));
    ASSERT_EQ(0, cbm_dep_link_cross_edges(st, ""));
    cbm_store_close(st);
    PASS();
}

TEST(test_cross_edges_record_file_owner) {
    cbm_store_t *st = cbm_store_open_memory();
    ASSERT_NOT_NULL(st);
    ASSERT_EQ(cbm_store_upsert_project(st, "dep-owner-test", "/tmp/project"), CBM_STORE_OK);
    ASSERT_EQ(cbm_store_upsert_project(st, "dep-owner-test.dep.requests", "/tmp/requests"),
              CBM_STORE_OK);

    cbm_node_t import_node = {0};
    import_node.project = "dep-owner-test";
    import_node.label = "Variable";
    import_node.name = "requests";
    import_node.qualified_name = "dep-owner-test.app.imports.requests";
    import_node.file_path = "app.py";
    import_node.start_line = 1;
    import_node.end_line = 1;
    import_node.properties_json = "{}";
    ASSERT_GT(cbm_store_upsert_node(st, &import_node), 0);

    cbm_node_t module_node = {0};
    module_node.project = "dep-owner-test.dep.requests";
    module_node.label = "Module";
    module_node.name = "requests";
    module_node.qualified_name = "dep-owner-test.dep.requests";
    module_node.file_path = "__init__.py";
    module_node.start_line = 1;
    module_node.end_line = 1;
    module_node.properties_json = "{}";
    ASSERT_GT(cbm_store_upsert_node(st, &module_node), 0);

    ASSERT_EQ(cbm_dep_link_cross_edges(st, "dep-owner-test"), 1);
    int node_owners = 0;
    int edge_owners = 0;
    ASSERT_EQ(cbm_store_count_file_delta_owners(st, "dep-owner-test", "app.py", &node_owners,
                                                &edge_owners),
              CBM_STORE_OK);
    ASSERT_EQ(edge_owners, 1);

    cbm_store_close(st);
    PASS();
}

TEST(test_auto_index_deps_config_limit_policy) {
    char cache_tmp[CBM_SZ_256];
    int n = snprintf(cache_tmp, sizeof(cache_tmp), "%s/cbm_dep_policy_XXXXXX", cbm_tmpdir());
    ASSERT(n > 0 && (size_t)n < sizeof(cache_tmp));
    ASSERT_NOT_NULL(cbm_mkdtemp(cache_tmp));
    cbm_config_t *cfg = cbm_config_open(cache_tmp);
    ASSERT_NOT_NULL(cfg);

    ASSERT_EQ(cbm_dep_auto_index_effective_limit(NULL, CBM_DEFAULT_AUTO_DEP_LIMIT), 0);
    ASSERT_EQ(cbm_dep_auto_index_effective_limit(cfg, CBM_DEFAULT_AUTO_DEP_LIMIT), 0);
    ASSERT_EQ(cbm_config_set(cfg, CBM_CONFIG_AUTO_INDEX_DEPS, "false"), 0);
    ASSERT_EQ(cbm_dep_auto_index_effective_limit(cfg, CBM_DEFAULT_AUTO_DEP_LIMIT), 0);
    ASSERT_EQ(cbm_config_set(cfg, CBM_CONFIG_AUTO_INDEX_DEPS, "true"), 0);
    ASSERT_EQ(cbm_config_set(cfg, CBM_CONFIG_AUTO_DEP_LIMIT, "7"), 0);
    ASSERT_EQ(cbm_dep_auto_index_effective_limit(cfg, CBM_DEFAULT_AUTO_DEP_LIMIT), 7);
    ASSERT_EQ(cbm_config_set(cfg, CBM_CONFIG_AUTO_DEP_LIMIT, "0"), 0);
    ASSERT_EQ(cbm_dep_auto_index_effective_limit(cfg, CBM_DEFAULT_AUTO_DEP_LIMIT), -1);
    ASSERT_EQ(
        cbm_dep_normalize_configured_limit(CBM_MAX_AUTO_DEP_LIMIT, CBM_DEFAULT_AUTO_DEP_LIMIT),
        CBM_MAX_AUTO_DEP_LIMIT);
    ASSERT_EQ(cbm_dep_normalize_configured_limit(-1, CBM_DEFAULT_AUTO_DEP_LIMIT),
              CBM_DEFAULT_AUTO_DEP_LIMIT);
    ASSERT_EQ(
        cbm_dep_normalize_configured_limit(CBM_MAX_AUTO_DEP_LIMIT + 1, CBM_MAX_AUTO_DEP_LIMIT + 1),
        CBM_DEFAULT_AUTO_DEP_LIMIT);
    ASSERT_NEQ(cbm_config_set(cfg, CBM_CONFIG_AUTO_DEP_LIMIT, "-1"), 0);
    char over_limit[CBM_SZ_32];
    snprintf(over_limit, sizeof(over_limit), "%d", CBM_MAX_AUTO_DEP_LIMIT + 1);
    ASSERT_NEQ(cbm_config_set(cfg, CBM_CONFIG_AUTO_DEP_LIMIT, over_limit), 0);

    cbm_config_close(cfg);
    cleanup_fixture_dir(cache_tmp);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  USAGE-RANKED DEPENDENCY SELECTION (cbm_discover_installed_deps)
 *
 *  When discovery finds more npm packages than max_results, the retained
 *  subset must be the most-imported ones (by distinct project import
 *  reference count), not merely the first declared. See
 *  notes/2026-07-21-2332-path-autoindex-dependency-asymmetry-analysis.md
 *  section 9.
 * ══════════════════════════════════════════════════════════════════ */

/* Create a temp dir with package.json declaring npm dependencies in the
 * given declaration order, each with a real node_modules/<name>/ directory
 * so cbm_resolve_pkg_source succeeds and discover_npm_deps retains it. */
static int setup_npm_rank_fixture(char *tmp_dir, size_t tmp_sz, const char *const *names,
                                  int name_count) {
    int n = snprintf(tmp_dir, tmp_sz, "%s/cbm_deprank_XXXXXX", cbm_tmpdir());
    if (n <= 0 || (size_t)n >= tmp_sz) return -1;
    if (!cbm_mkdtemp(tmp_dir)) return -1;

    char json[CBM_SZ_1K];
    size_t off = 0;
    int w = snprintf(json + off, sizeof(json) - off, "{\"name\":\"fixture\",\"dependencies\":{");
    if (w <= 0) return -1;
    off += (size_t)w;
    for (int i = 0; i < name_count; i++) {
        w = snprintf(json + off, sizeof(json) - off, "%s\"%s\":\"1.0.0\"", i > 0 ? "," : "", names[i]);
        if (w <= 0) return -1;
        off += (size_t)w;
    }
    w = snprintf(json + off, sizeof(json) - off, "}}\n");
    if (w <= 0) return -1;

    char path[CBM_SZ_1K];
    snprintf(path, sizeof(path), "%s/package.json", tmp_dir);
    FILE *fp = fopen(path, "w");
    if (!fp) return -1;
    fputs(json, fp);
    fclose(fp);

    for (int i = 0; i < name_count; i++) {
        char dep_dir[CBM_SZ_1K];
        snprintf(dep_dir, sizeof(dep_dir), "%s/node_modules/%s", tmp_dir, names[i]);
        if (!cbm_mkdir_p(dep_dir, 0700)) return -1;
    }
    return 0;
}

/* Insert a project-scoped Variable node standing in for one project import
 * reference to `package`, mirroring the node shape
 * cbm_dep_link_cross_edges() and rank_by_import_usage() match against
 * (label="Variable", project_exact, node.name == package name). */
static void insert_import_reference(cbm_store_t *store, const char *project, const char *package,
                                    int seq) {
    char qn[192];
    snprintf(qn, sizeof(qn), "%s.app.import.%d", project, seq);
    cbm_node_t n = {0};
    n.project = project;
    n.label = "Variable";
    n.name = package;
    n.qualified_name = qn;
    n.file_path = "app.py";
    n.start_line = 1;
    n.end_line = 1;
    n.properties_json = "{}";
    (void)cbm_store_upsert_node(store, &n);
}

TEST(test_discover_deps_ranks_by_import_usage) {
    char tmp[CBM_SZ_256];
    const char *names[] = {"pkg-a", "pkg-b", "pkg-c", "pkg-d", "pkg-e"};
    ASSERT_EQ(setup_npm_rank_fixture(tmp, sizeof(tmp), names, 5), 0);

    cbm_store_t *store = cbm_store_open_memory();
    ASSERT_NOT_NULL(store);
    const char *project = "rank-fixture";
    ASSERT_EQ(cbm_store_upsert_project(store, project, tmp), CBM_STORE_OK);

    /* pkg-c: 4 import references, pkg-a: 2, pkg-b: 1, pkg-d/pkg-e: 0. */
    int seq = 0;
    for (int i = 0; i < 4; i++) insert_import_reference(store, project, "pkg-c", seq++);
    for (int i = 0; i < 2; i++) insert_import_reference(store, project, "pkg-a", seq++);
    insert_import_reference(store, project, "pkg-b", seq++);

    cbm_dep_discovered_t *out = NULL;
    int count = 0;
    ASSERT_EQ(cbm_discover_installed_deps(CBM_PKG_NPM, tmp, store, project, &out, &count, 3), 0);
    ASSERT_EQ(count, 3);
    ASSERT_NOT_NULL(out);
    ASSERT_STR_EQ(out[0].package, "pkg-c"); /* 4 imports: most used */
    ASSERT_STR_EQ(out[1].package, "pkg-a"); /* 2 imports */
    ASSERT_STR_EQ(out[2].package, "pkg-b"); /* 1 import */

    cbm_dep_discovered_free(out, count);
    cbm_store_close(store);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_discover_deps_tiebreak_by_name_is_deterministic) {
    char tmp[CBM_SZ_256];
    /* Declaration order deliberately not alphabetical, so a passing test
     * proves the tiebreak sorts by name rather than preserving discovery
     * order for the zero-import packages. */
    const char *names[] = {"pkg-e", "pkg-b", "pkg-a", "pkg-d", "pkg-c"};
    ASSERT_EQ(setup_npm_rank_fixture(tmp, sizeof(tmp), names, 5), 0);

    cbm_store_t *store = cbm_store_open_memory();
    ASSERT_NOT_NULL(store);
    const char *project = "tiebreak-fixture";
    ASSERT_EQ(cbm_store_upsert_project(store, project, tmp), CBM_STORE_OK);

    /* Only pkg-c is imported; pkg-a, pkg-b, pkg-d, pkg-e all tie at zero
     * import references and must break the tie alphabetically. */
    insert_import_reference(store, project, "pkg-c", 0);

    cbm_dep_discovered_t *out = NULL;
    int count = 0;
    ASSERT_EQ(cbm_discover_installed_deps(CBM_PKG_NPM, tmp, store, project, &out, &count, 3), 0);
    ASSERT_EQ(count, 3);
    ASSERT_STR_EQ(out[0].package, "pkg-c"); /* the only imported package wins */
    ASSERT_STR_EQ(out[1].package, "pkg-a"); /* tie at 0 imports: alphabetical */
    ASSERT_STR_EQ(out[2].package, "pkg-b");

    cbm_dep_discovered_free(out, count);
    cbm_store_close(store);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_discover_deps_at_limit_preserves_discovery_order) {
    char tmp[CBM_SZ_256];
    const char *names[] = {"pkg-a", "pkg-b", "pkg-c"};
    ASSERT_EQ(setup_npm_rank_fixture(tmp, sizeof(tmp), names, 3), 0);

    cbm_store_t *store = cbm_store_open_memory();
    ASSERT_NOT_NULL(store);
    const char *project = "atlimit-fixture";
    ASSERT_EQ(cbm_store_upsert_project(store, project, tmp), CBM_STORE_OK);

    /* pkg-c is imported heavily, but candidate count (3) is AT the limit
     * (3), so ranking must not run: order must stay declaration order
     * (a, b, c) — byte-identical to pre-ranking behavior. */
    for (int i = 0; i < 5; i++) insert_import_reference(store, project, "pkg-c", i);

    cbm_dep_discovered_t *out = NULL;
    int count = 0;
    ASSERT_EQ(cbm_discover_installed_deps(CBM_PKG_NPM, tmp, store, project, &out, &count, 3), 0);
    ASSERT_EQ(count, 3);
    ASSERT_STR_EQ(out[0].package, "pkg-a");
    ASSERT_STR_EQ(out[1].package, "pkg-b");
    ASSERT_STR_EQ(out[2].package, "pkg-c");

    cbm_dep_discovered_free(out, count);
    cbm_store_close(store);
    cleanup_fixture_dir(tmp);
    PASS();
}

TEST(test_discover_deps_rank_query_failure_falls_back_to_discovery_order) {
    char tmp[CBM_SZ_256];
    const char *names[] = {"pkg-a", "pkg-b", "pkg-c", "pkg-d", "pkg-e"};
    ASSERT_EQ(setup_npm_rank_fixture(tmp, sizeof(tmp), names, 5), 0);

    cbm_store_t *store = cbm_store_open_memory();
    ASSERT_NOT_NULL(store);
    const char *project = "rankfail-fixture";
    ASSERT_EQ(cbm_store_upsert_project(store, project, tmp), CBM_STORE_OK);

    /* Corrupt the store so the import-usage query fails deterministically:
     * dropping `nodes` breaks cbm_store_search (used by rank_by_import_usage)
     * while npm discovery itself reads package.json directly from disk and
     * makes no store query, so discovery must still succeed. */
    sqlite3 *db = cbm_store_get_db(store);
    ASSERT_NOT_NULL(db);
    ASSERT_EQ(sqlite3_exec(db, "DROP TABLE nodes;", NULL, NULL, NULL), SQLITE_OK);

    cbm_dep_discovered_t *out = NULL;
    int count = 0;
    ASSERT_EQ(cbm_discover_installed_deps(CBM_PKG_NPM, tmp, store, project, &out, &count, 3), 0);
    ASSERT_EQ(count, 3);
    ASSERT_NOT_NULL(out);
    /* Fail-open: the ranking query failed, so declaration/discovery order
     * (a, b, c) is preserved rather than erroring or crashing. */
    ASSERT_STR_EQ(out[0].package, "pkg-a");
    ASSERT_STR_EQ(out[1].package, "pkg-b");
    ASSERT_STR_EQ(out[2].package, "pkg-c");

    cbm_dep_discovered_free(out, count);
    cbm_store_close(store);
    cleanup_fixture_dir(tmp);
    PASS();
}

/* ══════════════════════════════════════════════════════════════════
 *  SUITE
 * ══════════════════════════════════════════════════════════════════ */

SUITE(depindex) {
    /* MCP tool registration and validation */
    RUN_TEST(tool_index_dependencies_listed);
    RUN_TEST(tool_index_dependencies_missing_project);
    RUN_TEST(tool_index_dependencies_missing_packages);

    /* AI grounding: core vs dependency disambiguation */
    RUN_TEST(search_graph_default_excludes_deps);
    RUN_TEST(search_graph_include_deps_marks_source);
    RUN_TEST(trace_path_dependency_graph_uses_supported_schema);
    RUN_TEST(get_code_snippet_dep_shows_provenance);

    /* External node marking */
    RUN_TEST(build_def_props_no_external_when_null_ctx);

    /* QN prefixing */
    RUN_TEST(dep_qn_no_collision_with_project);

    /* Separate storage */
    RUN_TEST(dep_db_path_convention);

    /* Dependency discovery */
    RUN_TEST(dep_discover_skips_test_dirs);
    RUN_TEST(dep_discover_max_files_guard);

    /* Depindex helpers */
    RUN_TEST(test_parse_pkg_manager_valid);
    RUN_TEST(test_parse_pkg_manager_invalid);
    RUN_TEST(test_pkg_manager_str_roundtrip);
    RUN_TEST(test_dep_project_name_format);
    RUN_TEST(test_is_dep_project_with_session);
    RUN_TEST(test_is_dep_project_without_session);
    RUN_TEST(test_detect_ecosystem_python);
    RUN_TEST(test_detect_ecosystem_rust);
    RUN_TEST(test_detect_ecosystem_none);
    RUN_TEST(test_is_manifest_path);
    RUN_TEST(test_resolve_npm_node_modules);
    RUN_TEST(test_auto_index_npm_reads_actual_package_json_shape);
    RUN_TEST(test_discover_vendored_deps_unlimited_uses_actual_capacity);
    RUN_TEST(test_discover_manifest_deps_unlimited_saturates_query_limit);
    RUN_TEST(test_pipeline_set_project_name);
    RUN_TEST(test_dep_reindex_replaces);
    RUN_TEST(test_auto_index_deps_refreshes_nodes_fts);

    /* Result tagging */
    RUN_TEST(test_search_results_have_source_field);
    RUN_TEST(test_search_dep_results_tagged_dependency);
    RUN_TEST(test_search_response_has_session_project);

    /* Index status deps */
    RUN_TEST(test_index_status_shows_deps);

    /* Trace and snippet source tagging */
    RUN_TEST(test_trace_results_have_source_field);
    RUN_TEST(test_snippet_has_source_origin_field);
    RUN_TEST(test_cross_edges_null_safety);
    RUN_TEST(test_cross_edges_record_file_owner);
    RUN_TEST(test_auto_index_deps_config_limit_policy);

    /* Usage-ranked dependency selection */
    RUN_TEST(test_discover_deps_ranks_by_import_usage);
    RUN_TEST(test_discover_deps_tiebreak_by_name_is_deterministic);
    RUN_TEST(test_discover_deps_at_limit_preserves_discovery_order);
    RUN_TEST(test_discover_deps_rank_query_failure_falls_back_to_discovery_order);
}
