/** Domain copy stays beside the workspace, like the other exploration panels. */
export const architectureText = {
    title: 'Architecture',
    subtitle: 'Understand the structure. Follow the evidence.',
    summaryDetails: 'Index summary, layers and communities',
    importWalk: 'Read by import order',
    inspectEdges: 'Inspect edges',
    retainedEdges: (count: number, reported: number) => `${count} retained edges from a boundary reporting ${reported} calls. Package membership uses the same index rule as the summary. Counts may differ across bounds or index updates.`,
    edgeEvidenceUnavailable: 'No constituent edge is available in the loaded map snapshot. The summary count alone cannot establish a path or source location; refresh or inspect the source area.',
    views: { overview: 'Overview', dependencies: 'Dependencies', entryPoints: 'Entry points', routes: 'Routes', hotspots: 'Hotspots' },
    navigation: 'Architecture views',
    refresh: 'Refresh',
    reset: 'Reset view',
    filter: 'Filter this view',
    filterPlaceholder: 'Filter by name or path...',
    saved: 'View saved on this device',
    sessionOnly: 'View saved for this session only',
    loading: 'Reading project architecture...',
    unavailable: 'Architecture is not available yet.',
    chooseProject: 'Open an indexed project to explore its architecture.',
    loadFailed: 'Could not read the architecture.',
    retry: 'Try again',
    noMatches: 'No results match this filter.',
    noData: 'This summary contains no findings for this view.',
    sourceMissing: 'No source location was provided.',
    modules: 'Modules',
    moduleNote: 'Groups reported by the index. Select one to focus its relationships.',
    group: 'Group',
    symbols: 'Symbols',
    relations: 'Relations',
    files: 'Files listed',
    languages: 'Languages',
    dependsOn: 'Depends on',
    usedBy: 'Used by',
    calls: 'Calls',
    from: 'From',
    to: 'To',
    dependencyTitle: 'Calls between groups',
    dependencyNote: 'Arrows follow indexed calls. Select a group to filter its relationships.',
    tableTitle: 'Recorded relationships',
    mapLabel: 'Directed calls between architecture groups',
    layers: 'Architecture layers',
    layersNote: 'Inferred assignments from the provider.',
    clusters: 'Related communities',
    clustersNote: 'Groups inferred from call relationships.',
    source: 'Source',
    name: 'Name',
    method: 'Method',
    path: 'Route',
    handler: 'Handler',
    evidence: 'Evidence',
    evidenceSummary: 'About this view',
    evidenceDetail: 'These are static index findings. Layers and communities are inferred. Lists may be bounded by the provider; an empty list does not establish absence. Refresh after reindexing to read the new summary.',
    entryNote: 'Starting points identified by the index.',
    routeNote: 'Route discovery depends on the indexed language. Source matches are labeled separately.',
    hotspotNote: 'Measured signals to help choose what to inspect. These are not a quality score.',
    indexOrigin: 'Index',
    sourceOrigin: 'Source match',
    unknown: 'Not reported',
    fanIn: 'Callers',
    complexity: 'Complexity',
    cognitive: 'Cognitive',
    loopDepth: 'Loop depth',
    signals: 'Signals',
    allocationInLoop: 'Allocation in loop',
    scanInLoop: 'Scan in loop',
    unguardedRecursion: 'Unguarded recursion',
    showMore: 'Show more',
    filesTitle: 'Indexed files',
    kindsTitle: 'Symbol kinds',
    numberOfMembers: (count: number) => `${count.toLocaleString()} members`,
    mapLimit: (shown: number, omitted: number) => `${shown} groups in map · ${omitted} more groups in the table`,
    results: (shown: number, total: number) => `${shown.toLocaleString()} of ${total.toLocaleString()} shown`,
    openSource: (name: string) => `Open source: ${name}`,
    focusGroup: (name: string) => `Show relationships for ${name}`,
    groupStats: (symbols: number) => `${symbols.toLocaleString()} symbols`,
    cohesion: (value: number) => `${Math.round(value * 100)}% cohesion`,
};
