"""Python gRPC server fixture for IDL cross-repo binding tests.

Mirrors what protoc-gen-grpc-python emits: a base class named
PromoCodeServiceServicer that user code subclasses.

The cbm pass_idl_scan should detect:
  - The PromoCodeService Class node (extracted from contracts/promo.proto)
  - The INHERITS edge from PromoCodeServicer → PromoCodeServiceServicer
  - And emit HANDLES edges from each method on PromoCodeServicer to the
    corresponding __route__grpc__PromoCodeService/<method> Route node.
"""

# Stand-in for protoc-gen-grpc-python output. Real code would import this
# from generated promo_pb2_grpc.
class PromoCodeServiceServicer:
    """Generated by protoc — placeholder so the test fixture stands alone."""
    def GetVoucher(self, request, context):
        raise NotImplementedError

    def RedeemVoucher(self, request, context):
        raise NotImplementedError


class PromoCodeServicer(PromoCodeServiceServicer):
    def __init__(self, store):
        self._store = store

    def GetVoucher(self, request, context):
        voucher = self._store.get(request.voucher_id)
        return voucher

    def RedeemVoucher(self, request, context):
        ok = self._store.redeem(request.voucher_id, request.user_id)
        return ok
