"""Python gRPC client fixture for IDL cross-repo binding tests.

Mirrors what protoc-gen-grpc-python emits: a stub class
PromoCodeServiceStub instantiated with a channel; rpcs are invoked as
methods on the stub instance.

The cbm pass_idl_scan should detect:
  - The `stub` variable assigned to type `PromoCodeServiceStub` (suffix `Stub`)
  - Strip the `Stub` suffix → service name `PromoCodeService`
  - Match against the proto-derived `PromoCodeService` Class node
  - For each `stub.<RpcName>(...)` call within `fetch_voucher`, emit a
    `GRPC_CALLS` edge to the Route node
    `__route__grpc__PromoCodeService/<RpcName>` with `{service, method}` props.
"""

# Stand-in for protoc-gen-grpc-python output. Real code imports promo_pb2_grpc.
class PromoCodeServiceStub:
    """Generated by protoc — placeholder to keep the fixture buildable in isolation."""
    def __init__(self, channel):
        self._channel = channel

    def GetVoucher(self, request, timeout=None):
        return None

    def RedeemVoucher(self, request, timeout=None):
        return None


def fetch_voucher(channel, voucher_id):
    stub = PromoCodeServiceStub(channel)
    response = stub.GetVoucher({"voucher_id": voucher_id})
    return response


def redeem_voucher(channel, voucher_id, user_id):
    stub = PromoCodeServiceStub(channel)
    response = stub.RedeemVoucher({"voucher_id": voucher_id, "user_id": user_id})
    return response.success
