#!/usr/bin/env python3
"""Generate the deterministic repository shelf and file index."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "REPOSITORY_INDEX.md"
LAYOUT = ROOT / "docs" / "repository-layout.json"


def resolve_git() -> str:
    explicit = os.environ.get("GIT_EXECUTABLE")
    if explicit:
        located = shutil.which(explicit)
        if located:
            return located
        if Path(explicit).is_file():
            return explicit
    located = shutil.which("git")
    if located:
        return located
    for variable in ("ProgramFiles", "ProgramFiles(x86)"):
        base = os.environ.get(variable)
        if base:
            candidate = Path(base) / "Git" / "cmd" / "git.exe"
            if candidate.is_file():
                return str(candidate)
    return "git"


GIT = resolve_git()


def tracked_files() -> list[str]:
    result = subprocess.run(
        [GIT, "ls-files", "--cached", "-z"],
        cwd=ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode:
        detail = result.stderr.decode("utf-8", errors="replace").strip()
        raise RuntimeError(f"git ls-files failed: {detail}")
    return sorted(item.decode("utf-8") for item in result.stdout.split(b"\0") if item)


def read_index_text(path: str | Path) -> str:
    """Read a file exactly as staged, without consulting the working tree."""
    relative = path.relative_to(ROOT).as_posix() if isinstance(path, Path) else path
    result = subprocess.run(
        [GIT, "show", f":{relative}"],
        cwd=ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode:
        detail = result.stderr.decode("utf-8", errors="replace").strip()
        raise RuntimeError(f"cannot read staged {relative}: {detail}")
    return result.stdout.decode("utf-8")


def below(files: list[str], prefix: str) -> list[str]:
    normalized = prefix.rstrip("/") + "/"
    return [path for path in files if path.startswith(normalized)]


def direct_files(files: list[str], prefix: str) -> list[str]:
    normalized = prefix.rstrip("/") + "/"
    return sorted(
        path[len(normalized) :]
        for path in files
        if path.startswith(normalized) and "/" not in path[len(normalized) :]
    )


def render() -> str:
    files = tracked_files()
    layout = json.loads(read_index_text(LAYOUT))
    shelves: dict[str, dict[str, str]] = layout["shelves"]
    modules: dict[str, str] = layout["srcModules"]
    package_shelves: dict[str, str] = layout["packageShelves"]
    wrappers = [path for path in files if path.startswith("internal/cbm/grammar_") and path.endswith(".c")]
    grammar_dirs = {
        path.split("/")[4]
        for path in files
        if path.startswith("internal/cbm/vendored/grammars/") and len(path.split("/")) > 5
    }
    direct_tests = [path for path in direct_files(files, "tests") if path.startswith("test_") and path.endswith(".c")]
    repro_tests = [path for path in direct_files(files, "tests/repro") if path.startswith("repro_") and path.endswith(".c")]
    frontend_tests = [path for path in below(files, "graph-ui/src") if path.endswith((".test.ts", ".test.tsx"))]

    lines = [
        "# Repository Index",
        "",
        "> Generated by `scripts/generate-repository-index.py`. Do not edit by hand.",
        "",
        "This is the repository catalog. Start here when deciding where a new file belongs.",
        "",
        "The inventory uses Git's staged index. Stage an intended new file before",
        "regenerating the catalog so local scratch files cannot change checked-in counts.",
        "",
        "## Maintained shelves",
        "",
        "| Shelf | Purpose | Owner | Tracked files |",
        "| --- | --- | --- | ---: |",
    ]
    for shelf, metadata in sorted(shelves.items()):
        lines.append(f"| `{shelf}/` | {metadata['purpose']} | `{metadata['owner']}` | {len(below(files, shelf))} |")

    lines.extend(
        [
            "",
            "## Verified inventory",
            "",
            f"- {len(wrappers)} grammar wrappers and {len(grammar_dirs)} vendored grammar directories.",
            f"- {len(direct_tests)} required direct C test files and {len(repro_tests)} reproduction files.",
            f"- {len(below(files, 'graph-ui/src'))} frontend source files, including {len(frontend_tests)} test files.",
            f"- {len(package_shelves)} declared distribution shelves.",
            "",
            "## Product modules",
            "",
            "| Module | Responsibility | Direct files |",
            "| --- | --- | ---: |",
        ]
    )
    for module, purpose in sorted(modules.items()):
        lines.append(f"| `src/{module}/` | {purpose} | {len(direct_files(files, f'src/{module}'))} |")

    lines.extend(["", "## Module file catalog", ""])
    for module in sorted(modules):
        names = ", ".join(f"`{name}`" for name in direct_files(files, f"src/{module}"))
        lines.extend([f"### `src/{module}/`", "", names, ""])

    root_names = ", ".join(f"`{name}`" for name in layout["rootFiles"])
    lines.extend(["## Governed root files", "", root_names, ""])

    lines.extend(
        [
            "## Distribution shelves",
            "",
            ", ".join(f"`pkg/{name}/` ({purpose})" for name, purpose in sorted(package_shelves.items())),
            "",
            "All active distribution versions derive from root `VERSION`. Published artifact",
            "checksums are cataloged in `pkg/release-checksums.json`.",
            "",
            "## Stable entry points",
            "",
            "| Need | Command or document |",
            "| --- | --- |",
            "| Find a command | `make help` |",
            "| Build product | `make build` |",
            "| Run required C tests | `make test` |",
            "| Build and test frontend | `make frontend` |",
            "| Check repository organization | `make organization` |",
            "| Regenerate this index | `make repository-index` |",
            "| Understand runtime boundaries | `docs/ARCHITECTURE.md` |",
            "| Route a review | `.github/CODEOWNERS` and `MAINTAINERS.md` |",
            "| Add or update documentation | `docs/README.md` |",
            "",
            "## Placement rules",
            "",
            "1. Put product code in the narrowest existing `src` module.",
            "2. Put extraction and language work in `internal/cbm`; keep third-party grammar",
            "   sources below its `vendored` boundary.",
            "3. Put required C suites directly in `tests` and register them in `Makefile.cbm`",
            "   and `tests/test_main.c`. Put open-bug reproduction cases in `tests/repro`.",
            "4. Put React code only below `graph-ui/src`. Build output and TypeScript build",
            "   metadata are never source files.",
            "5. Put package-manager metadata under its matching `pkg` shelf and update it",
            "   through `scripts/sync-version.py`.",
            "6. Regenerate this index and run `make organization` after adding a shelf or module.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the checked-in index is stale")
    args = parser.parse_args()
    expected = render()
    if args.check:
        try:
            actual = read_index_text(OUTPUT)
        except RuntimeError:
            actual = ""
        if actual != expected:
            print("ERROR: docs/REPOSITORY_INDEX.md is stale; run make repository-index", file=sys.stderr)
            return 1
        print("repository index: current")
        return 0
    with OUTPUT.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(expected)
    print("generated docs/REPOSITORY_INDEX.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
